### ISSUE TITLE
User list and tab completion does not update after /nick

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#102]
Users disappear and appear just fine when they connect or disconnect, but if they /nick quasselweb does not change their name in either the nick list or the tab completion.
Disconnecting and reconnecting will reupdate everything correctly.

**Comment by tecknojock** [comment]
So when the patch was pushed that enabled cycling of tab completion, this broke once more it seems. Or it might have been another patch, but I remember that happening when I applied that update.

**Comment by magne4000** [comment]
`libquassel @0.9.4` fixes it, you can run `npm update` !
