### ISSUE TITLE
Add support for first connection setup

### ISSUE THREAD

**Issue by magne4000** [magne4000/quassel-webserver#109]
https://gist.github.com/justjanne/71be557c670937d6ee93

**Comment by tecknojock** [comment]
So first connect to a server initiates teh connection but doesnt display anything in the server buffer til you refresh the page.

**Comment by tecknojock** [comment]
Also the use ssl tick mark box doesnt seem to persist.

**Comment by magne4000** [comment]
This is fixed by `libquassel 1.1.9`
