### ISSUE TITLE
Custom highlights/highlight on all nicks in identity

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#110]
Being able to have custom highlights for a user, ideally stored on the (proxy)server, would be really nice. 

Though, if the feature of being able to highlight on all nicks was adopted as it is in quasseldroid, that would still be a major step up.

**Comment by magne4000** [comment]
I think that adding highlights for all identities should be feasible (like on QD http://imgur.com/2E3uvIp).
Custom highlights too, but storing them on the server part of quassel-webserver is not something that I will do for now, as it will require some sort of storage that I don't want to implement, in order to keep the server side as simple as possible.

**Comment by magne4000** [comment]
@2f0088b

**Comment by tecknojock** [comment]
Hmm, the commit doesn't seem to do more than add a tick box in the options. I'm not getting any highlights on anything other than my present nick.

**Comment by magne4000** [comment]
Even after a reload ?

**Comment by magne4000** [comment]
Oh I know, you probably forgot to `npm update`, that's a fix in `libquassel`

**Comment by tecknojock** [comment]
My start line is always:
git pull && npm update && npm prune && npm update && node app.js

So no, npm update is done.
And my settings have been as such for several browser restarts and server restarts: http://candyhor.se/files/GyroTech/file_311.jpg

**Comment by tecknojock** [comment]
Perfect! That fixed the highlight on all nicks :D

**Comment by tecknojock** [comment]
Heh! I just encountered a small bug. Hilight on all nicks only triggers on nicks in your account. If I change my nick to something besides that, then it wont ping on that new nick.
Example:
Nicks on account <GyroTech Serilde Ruzeth>
Present nick is GyroFeather
any message containing GyroFeather wont ping, but any containing the other nicks will.

**Comment by magne4000** [comment]
Fixed by `libquassel 1.1.8`

**Comment by tecknojock** [comment]
Perfect! Thanks ^^
