### ISSUE TITLE
Ability to insert formatting characters

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#111]
It'd be nice to be able to insert the irc formatting characters, ^i (italics), ^b (bold), ^u (Underline), and ^k\d\d,\d\d (Colors)

I'm not sure what the best way to go about implementing this would be, but it'd be neat.

**Comment by magne4000** [comment]
Implemented with last commits (`v1.2.0`). It will need some beta testing I suppose.

**Comment by tecknojock** [comment]
Awesome! 
I have found 1 small bug though. When you use colors, you cant stop using colors till you send it. Probably needs a way to terminate it in the UI

**Comment by magne4000** [comment]
That is a valid point, I'll add another control for this
