### ISSUE TITLE
Core Dump

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#115]
Not sure what causes this: I just noticed that the core dumped with this error message:

node: ../src/node_zlib.cc:124: static void node::ZCtx::Write(const v8::FunctionCallbackInfo<v8::Value>&) [with bool async = true]: Assertion `(false) == (ctx->pending_close_ && "close is pending")' failed.
Aborted (core dumped)

I am running n latest and the lastest version of quassel-webserver.

**Comment by magne4000** [comment]
You should perhaps use an older version of nodejs. It's probably a nodejs bug as the nodejs part of quassel-webserver does almost nothing (it's just a proxy), so very unlikely to core dump.

**Comment by magne4000** [comment]
Closing this, reopen if it happens again
