### ISSUE TITLE
Favicon highlight indicator has become tiny

### ISSUE THREAD

**Issue by Gnarfoz** [magne4000/quassel-webserver#118]
Honey, I shrunk the icons :grin: 
![image](https://cloud.githubusercontent.com/assets/65654/13046060/f9150dca-d3d6-11e5-925f-2750c71cc116.png)

**Comment by Gnarfoz** [comment]
Weird, it only seems to happen on the first highlight in a session?
It has returned to its regular sized self:

![image](https://cloud.githubusercontent.com/assets/65654/13046351/85af1414-d3d8-11e5-8c0b-d4106da2f5a7.png)

**Comment by magne4000** [comment]
I'm unable to reproduce this one

**Comment by Gnarfoz** [comment]
Yeah, so am I now. :|
Maybe it was a Chrome bug or some caching effect...
It seems to work reliably now.

I'll reopen this, if I ever see it again. :D
