### ISSUE TITLE
Ignore list

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#121]
It would be nice if Quasselweb would respect the core's ignore list.

**Comment by magne4000** [comment]
It does, so you probably have a use case in which it doesn't work. Could you list the failing ignore rules you have ?

**Comment by tecknojock** [comment]
http://screencast.com/t/oVHNlSPM

There's my ignore rule that isnt working.

**Comment by magne4000** [comment]
`libquassel 0.9.7` fixes that, so you can `git pull && npm update`
