### ISSUE TITLE
Ability to edit ignore list

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#122]
It'd be nice if you could edit the ignore list in web app, now that the ignore list is supported.

Especially with support for clicking on someone and adding them to the ignore list.

**Comment by magne4000** [comment]
The ignore list can already be modified 
![image](https://cloud.githubusercontent.com/assets/1098371/13244903/0fc787b2-da0a-11e5-8248-5adccb88429f.png)

I created #123 for full context menu support for the users.
