### ISSUE TITLE
Cursor overwrites text in input field instead of inserting

### ISSUE THREAD

**Issue by rodneyrod** [magne4000/quassel-webserver#126]
Can be reproduced by typing something, then clicking anywhere in the previously typed text area.

**Comment by magne4000** [comment]
What browser do you use ? I'm unable to reproduce this on Chrome/Firefox under Windows 7.

**Comment by rodneyrod** [comment]
Chromium 48.0.2564.8 on Windows 10

**Comment by tecknojock** [comment]
Have you, by chance, hit your insert button? The input field actually respects insert rather unlike most fields on the internet.

**Comment by rodneyrod** [comment]
That could be a possibility, I checked again and the issue appears to be gone, think we can close this one for bow.
