### ISSUE TITLE
support Microsoft Edge

### ISSUE THREAD

**Issue by TheOneRing** [magne4000/quassel-webserver#129]

**Comment by magne4000** [comment]
I tried Microsoft Edge and did not had any issue. Could you paste the browser's console log ?

**Comment by magne4000** [comment]
I just pushed a new version of `libquassel` with up to date dependencies, perhaps it fixes your issue. Could you `npm update` and see if you have any difference ?

**Comment by magne4000** [comment]
Still same result : https://paste.kde.org/prdhqfvb8/imjlon

**Comment by willrea** [comment]
In Edge, with current checkout and npm updated the page hangs when connecting to quassel-core with the tab not responding. Only thing to come up in the console:

> AngularJS loaded
> angular-init.js (307,5)
> 
> Connecting to quasselcore
> angular-controller.js (631,9)

Similar behavior occurring on W10M also.

**Comment by magne4000** [comment]
I reproduced the issue with last Edge Preview VM

**Comment by magne4000** [comment]
It's an Edge issue with `.slice(...)` method : https://connect.microsoft.com/IE/feedbackdetail/view/2207846/buffer-uint8array-regression-in-latest-edge

**Comment by magne4000** [comment]
:arrow_right: `npm update`
`libquassel 1.0.1` fixes that before Edge does :smile:

**Comment by glasspelican** [comment]
looks like this fix also allows the app to work on the native blackberry10 browser
