### ISSUE TITLE
Shared chat list on the core

### ISSUE THREAD

**Issue by burukuru** [magne4000/quassel-webserver#130]
Just upgraded from a very old version and few things have changed on the chat list.
Used to be able to load a chat list from the server with all my unwanted channels hidden.
Now it seems that the list of hidden channel lists is held locally.

Is there a chance to have an option for the old functionality back? Ideally something like the official client where you can choose the chat list. Thanks!

**Comment by magne4000** [comment]
The hidden channel list is still fetched from the core, so it seems that you perhaps have an issue somewhere. Check your configuration file and empty all cache/localStorage from your browser.

**Comment by burukuru** [comment]
Which conf file?
I had issues in Firefox and I hid some chats.
Logged in via Chrome (never used before for quasselweb) and all the channels were still visible.

Are you loading/saving to a specific chat list that I removed perhaps?

**Comment by magne4000** [comment]
`settings-user.js` is the config file that I'm talking about.

The webserver doesn't store anything, it really acts as a regular client.

Perhaps you have javascript errors in your browser's console, can you check that ?

**Comment by tecknojock** [comment]
While it does load from the core, I believe it loads the first chat list alphabetically, so if you have multiple chat lists it will use that one.

**Comment by tecknojock** [comment]
Ahh sorry, you asked me to comment on this the other day. What I meant is if you have multiple chat lists available in the core, quassel-web, like quasseldroid will pick the first list, in alphabetical order (Say you have 'All Chats' and 'Regular Chats' it will pick the list 'All Chats'

I was mostly clarifying for burukuru. I for the record, feel like this behavior is fine.

**Comment by magne4000** [comment]
I had totally forgotten that this feature even exists ...

**Comment by tecknojock** [comment]
Its incredibly useful when you want more organization in your desktop client. I have 1 panel w/ 2 tabs that are all chats, and the chats I tend to hang care about more.

Then I have a 3 tab PM panel. 1 with all PMs, 1 with PMs from people who are presently arround, and 1 with the users I PM regularly. Then I have another panel that acts as a hilight alert.

http://imgur.com/godIgF5

Note the AA Preferred to make it the list quassel web and quasseldroid picks.

**Comment by burukuru** [comment]
That's interesting. I have 3 chat lists and only one starting with A - Active.
As far as I can see, that's not the one that's loading. Strangely enough, quasseldroid loads the same chat list as the web client.
When I open this in Chrome, I get a different list than when I open it in Firefox.

If I create a new list with 'AA' in the name, all works as you describe. Must be loading some stale chat list in the DB.

**Comment by burukuru** [comment]
I just worked around this by recreating my chat lists.
Thanks for your help figuring it out!
