### ISSUE TITLE
Error: read ECONNRESET crashes

### ISSUE THREAD

**Issue by burukuru** [magne4000/quassel-webserver#131]
I'm getting the following errors when quasselweb crashes:

`Connected to localhost:4242 (7da6d8906dcaa5d70818c5ecc2806daaccc8a6de73f9f77d73b9f085b152a862)
POST /p/connect 200 25.687 ms - 138
Forwarding socket with token 7da6d8906dcaa5d70818c5ecc2806daaccc8a6de73f9f77d73b9f085b152a862
TCP connection closed by remote (7da6d8906dcaa5d70818c5ecc2806daaccc8a6de73f9f77d73b9f085b152a862)
Websocket connection closed (7da6d8906dcaa5d70818c5ecc2806daaccc8a6de73f9f77d73b9f085b152a862)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:837:11)
    at TCP.onread (net.js:544:26)`

Is it just the connection to the core being reset and causing quasselweb to crash?
Is there a debug mode I can run this in?

**Comment by magne4000** [comment]
check in your browser and in quasselcore if you have other errors, the useful information are usually there.

**Comment by burukuru** [comment]
Had a look at the browser and no errors there. Sounds like it might be an issue with the core.
I'll need to run it in debug mode or something to see more detail.

**Comment by magne4000** [comment]
Closing this for now. Feel free to reopen it of needed
