### ISSUE TITLE
Show/Hide chat pop up doesn't show fully

### ISSUE THREAD

**Issue by burukuru** [magne4000/quassel-webserver#132]
On the last few items of a network, the show/hide chat doesn't show fully, gets drawn below  some elements.
![screen shot 2016-03-08 at 11 00 00](https://cloud.githubusercontent.com/assets/3882632/13599841/277e68f8-e51d-11e5-8779-84a947358ec5.png)

**Comment by magne4000** [comment]
Could you specify which browser you are using ?

**Comment by burukuru** [comment]
Firefox 44.0.2 on Mac
