### ISSUE TITLE
Bug: Items pasted in <> dont copy paste properly

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#142]
If you type `<test> `you can send it just fine, but if you then copy that `<test>` from your buffer and then paste it, it doesn't appear.

Huh...oddly enough  items in <> dont appear in the github messages...

**Comment by magne4000** [comment]
I do not have this issue, neither with Chrome nor Firefox. What OS/browser are you using ?

**Comment by tecknojock** [comment]
I'm using chrome on windows 7. I am using the latest version of quasselweb. Is there any other info I can give you? I've tried it with all plugins disabled, so it doesnt appear to be a pluggin issue.

**Comment by magne4000** [comment]
Oh ok, I reproduced it, I don't know what I was doing because it's quite obvious to replicate ...
