### ISSUE TITLE
Bug: Joins/parts dont show any info

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#144]
Joins and parts do not show any info about who is joining and parting in the Dev build:

19:18:26	-->	 has joined
19:19:12	<--	 has quit (Client Quit)
19:19:33	-->	 has joined

**Comment by tecknojock** [comment]
Mostly fixed. Joins, parts, and quits work for everyone, however nicks only work for other people.

Switching your own nick looks like: 09:27:06	<->

**Comment by magne4000** [comment]
Should be fixed, I was misusing `$compile`
