### ISSUE TITLE
Bug: Tab complete sometimes returns cursor to start of the line

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#147]
Sometimes when I tab complete the cursor jumps to the front of the input box without tab completing. I have no clue what triggers this behavior.

**Comment by magne4000** [comment]
The cursor seems to come back to the beginning of the line when I press tab quickly after another character

**Comment by magne4000** [comment]
@tecknojock Could you tell me if after this commit you still have the problem ?

**Comment by tecknojock** [comment]
Hmm just had it happen to me again

**Comment by tecknojock** [comment]
Hmmm...I havnt had this happen in a while...maybe its been inadvertently fixed?

**Comment by magne4000** [comment]
With last rework on tab completion, you still reproduce this ?

**Comment by tecknojock** [comment]
I think that this has indeed been fixed.
