### ISSUE TITLE
Dont consider @ for tab complete

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#156]
So espeically for using say bitlbee for irc -> telegram and irc -> telegram usernames require their name to be prefaced with an @ symbol. Since already an @ cant be apart of a user name, can you make it so that tab complete doesnt use this when searching for names, and treat it as if it was a " " or something.

Same goes for " and ' and ( and < please

**Comment by magne4000** [comment]
I'm not sure to understand. What is the actual behavior currently when tab-completing @... nicks, and what seems not to work as intended ?

**Comment by tecknojock** [comment]
Rightnow say I want to tab complete a person in discord named Xiagu. I cant go "@Xia"[tab] to get "@Xiagu" I have to go @ Xi[tab][ctrl+left][backspace][ctrl+right] or just type out @Xiagu in its entirety.

**Comment by magne4000** [comment]
Now I get it :sunglasses:
