### ISSUE TITLE
"Add a Network" button does nothing when no identities are defined

### ISSUE THREAD

**Issue by uwap** [magne4000/quassel-webserver#157]
It should display an error message instead.

**Comment by uwap** [comment]
A possible solution could be the following:

In $scope.configNetwork we add:
```
if ($quassel.get().identities.size === 0) {
  $scope.configIdentities();
  return;
}
```

The problem with it is that it takes a lot of time each time we press the "Add a Network" button. I saw there is something like initialization stuff in the code too, like an initialization dialog for the first log in? If so, it doesn't appear to work for me because not having initialized the account is the only possibility this bug could happen.

**Comment by magne4000** [comment]
The prompt was only shown after the first "setup successful" message. Now it also shows up at connection or when clicking Add a network if no identity is defined.

**Comment by uwap** [comment]
Thank you :)
