### ISSUE TITLE
Use HTML5 Desktop Notifications under Firefox for Linux

### ISSUE THREAD

**Issue by uwap** [magne4000/quassel-webserver#158]
I would fancy an option to allow the usage of HTML5 desktop notifications on highlight.

**Comment by magne4000** [comment]
It's already the case

**Comment by uwap** [comment]
Huh? I didn't notice that. Is there an option to enable or disable it?

**Comment by magne4000** [comment]
Your browser should have shown you the authorization message for enabling notifications. If not, there's something wrong. What browser do you use, and on what OS ?

**Comment by uwap** [comment]
I'm using firefox on Arch Linux. It doesn't ask me to enable notifications when setting the permission to "always ask". Furthermore it doesn't notify me when I get mentioned when I set the notifications to "allow" in the browser page settings.

**Comment by uwap** [comment]
Interestingly: When logging out from quassel it asks me if I want to enable notifications. I will try to investigate it further, but first I'm focussing on #157.

**Comment by magne4000** [comment]
Did you manage to gather some information on your issue ?

**Comment by uwap** [comment]
Nope. I haven't figured it out yet.

**Comment by uwap** [comment]
I assume the problem was on my end because it seems to work now.
