### ISSUE TITLE
Tab complete strips formatting.

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#161]
If you have a shift+enter break in a message and then you tab complete, it will remove the shift+enter break. 

Same thing happens with any other formatting options, italics, bolds, colors, underlines, etc.

**Comment by magne4000** [comment]
Tab completion removes formatting for now. It's the only way I found to still have something maintainable.
I'll keep the issue open at very low priority, and I'm not really sure I'll ever fix this.

**Comment by tecknojock** [comment]
Hmmm can you not run the tab complete on teh innerhtml instead of the innertext and replace the same? Though...I suppose that might muck with the cursor location

**Comment by magne4000** [comment]
Tab completing with innerhtml is too complicated, but one thing that's probably doable, is to autocomplete as for now, but instead of inserting the text as is, trying to insert the completion token at the current caret position.

**Comment by tecknojock** [comment]
Oh wow, this will even allow tab completion between formatting styles. That's something basically no client supports. That is very neat.

I have encountered one minor bug regarding this and line breaks. If you're on the first character of a new line, it regards it as an extention of the previous word

Zeroitame
Zer[tab] 

fails to tab to Zeroitame but say
Zeroitame:
Zer[tab] = Zeroitame

**Comment by magne4000** [comment]
Also this implementation doesn't fix the characters case
```
MA<tab> -> MAgne instead of Magne
```

**Comment by magne4000** [comment]
With last commit, on tab completion, it keeps the format that was applied to the first character of the completion token; i.e. for `MA<tab> -> Magne`, the format of the letter M is applied to the completed nick.
