### ISSUE TITLE
libquassel v1.1.11 not found

### ISSUE THREAD

**Issue by tinnvec** [magne4000/quassel-webserver#163]
`No compatible version found: libquassel@'>=1.1.11 <1.2.0'`

When updating to quassel-webserver v2.0.1, I get the above error.

As a work around, I just bumped it down to 1.1.10 in the package.json, as that is the closest version listed in the rest of the error message..

**Comment by magne4000** [comment]
Yeay, I just forgot to publish it ... sorry. That's all good now
