### ISSUE TITLE
Input Box Multiline Up and Down Arrow support

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#168]
When a message begins to span multiple lines in the input box, in most boxes, one could hit either up or down to move within the box, but in quassel web, it instead triggers the previous post, next post bit.

It'd be desirable if previous post was only triggered when trying to hit up from the top line and next post was only triggered when trying to hit down on the bottom line.

**Comment by magne4000** [comment]
Indeed one use case I did not take into account

**Comment by magne4000** [comment]
I think I can do that by testing if the position of the caret changes when I press up arrow. If it changes it means that I do not have to fetch previous message.

**Comment by tecknojock** [comment]
Hmmmm...well an up at the middle of the line will return the cursor to the start, and a down will bring it to the end. But this might be desirable anyways.

**Comment by magne4000** [comment]
Now we almost have same behavior as official client.
The one thing that I did not do quite the same is the fact that, on official client, it adds the content of the input to the history each time you press `↓` (for unsent messages).
On quassel-webserver it only adds the content on `↑` press. Pressing `↓` on unset message just empty the input.

**Comment by tecknojock** [comment]
Hmm might I ask why down doesn't add to input history? The behavior seems ideal as otherwise one might lose a message, and it doesn't seem to sacrifice anything to add it to the buffer. 

Both these issues came to my attention when one of my users was rather frustrated to lose a multi paragraph RP post that they were just about done writing and hit an arrow key to move the cursor to correct something. QuasselDroid follows the same behavior as the core client as well, for just that reason.

**Comment by magne4000** [comment]
Ok, convincing argument, I'll implement it :+1:

**Comment by tecknojock** [comment]
Hmm a small minor glitch with this one. Sometimes hitting up or down will return it to the beginning or end instead of cycling. Its not really that big a deal, but it only seems to happen when you hit things too quickly, like w/ the tab complete bug.
