### ISSUE TITLE
It is possible to overwrite history buffers

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#170]
So...I wanted to call this to attention, but I'm not actually clear what is the best method to handle this case anyways.

Say you have the following history posts in your up buffer

Message1
Message2
Message3

Now you're about to type message4, but instead of typing it, you first hit up til you reach message 2, then delete message 2 and type message 4 there. If you hit enter, your buffer looks as such:

message1
message2
message3
message4

however if you change your mind perhaps, and then hit up t go to message1 or hit down to go to message3 after typing message 4, the history buffer looks like:

message1
message4
message3

I think perhaps the best solution is to append message 4 to the end, or maybe only allowing the tweaking of messages that haven't been sent and otherwise appending it to the end.

**Comment by magne4000** [comment]
I though I reproduced the behavior of official client, but I hadn't noticed that the history is not really updatable as I did.
In official client, you can edit every message in history, but as soon as you send a message to the core, the history is set back to original values, that's what I should also do.

**Comment by magne4000** [comment]
Also noticed that history is shared across buffers in official clients, but I separated history per buffer in quassel-webserver. Don't know which one is better, perhaps you have some remark on this ?

**Comment by tecknojock** [comment]
The official client the history being shared across buffers is the default, but the history being per buffer is a setting, one that I always opt to turn on.  I do notice that quassel web does a slightly hybrid version of this, given that the history is per buffer, but the current typed message is not per buffer.

I think ideally would be to go all the way one or the other (I'd lean both input and history per buffer), or better yet have a setting, just like in the official client.
