### ISSUE TITLE
Bug: Certain strings yield vertical messages

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#173]
The following message yields a strange vertical message:
`bishbot <flowbish 🍬 🍭> I could do that`
The part that seems to be messing it up is specifically:
`<flowbish 🍬 🍭>`
other names on the relay without emoji in them dont break it.

https://candyhor.se/tiercel/GyroTech/BaSHmd.jpg

**Comment by magne4000** [comment]
On which OS, with which browser ?

**Comment by tecknojock** [comment]
Ohhh....Hmmm actually I just thought to disable my emojifi plugin. Its a combination of that plugin and something with that string, because its fine now. Odd since its behaved until now. Anyways I suppose we can close this since you cant really be diagnosing plugin incompatibilities. 

Win7 and the latest chrome for details.

**Comment by tecknojock** [comment]
Yep just changed emoji extensions. This one looks nicer and is compatible.
