### ISSUE TITLE
1.3.0 depends on libquassel: *

### ISSUE THREAD

**Issue by rejinka** [magne4000/quassel-webserver#177]
I think i ran into this one...

angular-controller.js:101 Uncaught TypeError: network.getBufferHashMap is not a function(anonymous function) @ angular-controller.js:101(anonymous function) @ ng-quassel.js:106EventEmitter.emit @ libquassel.js:16165Quassel.handleMsgType @ libquassel.js:21096Quassel.dispatch @ libquassel.js:21847(anonymous function) @ libquassel.js:21960EventEmitter.emit @ libquassel.js:6810handleData @ libquassel.js:16756(anonymous function) @ libquassel.js:16722EventEmitter.emit @ libquassel.js:6810readableAddChunk @ libquassel.js:8231Readable.push @ libquassel.js:8190gotBuffer @ libquassel.js:20030(anonymous function) @ libquassel.js:20041
3libquassel.js:20394 Uncaught TypeError: Cannot read property 'addUser' of nullNetwork.setIrcUsersAndChannels @ libquassel.js:20394Glouton.devour @ libquassel.js:61Quassel.handleInitDataNetwork @ libquassel.js:21861Quassel.handleStruct @ libquassel.js:21718Quassel.dispatch @ libquassel.js:21849(anonymous function) @ libquassel.js:21960EventEmitter.emit @ libquassel.js:6810handleData @ libquassel.js:16756(anonymous function) @ libquassel.js:16722EventEmitter.emit @ libquassel.js:6810readableAddChunk @ libquassel.js:8231Readable.push @ libquassel.js:8190gotBuffer @ libquassel.js:20030(anonymous function) @ libquassel.js:20041
6angular-controller.js:101 Uncaught TypeError: network.getBufferHashMap is not a function(anonymous function) @ angular-controller.js:101(anonymous function) @ ng-quassel.js:106EventEmitter.emit @ libquassel.js:16165Quassel.handleStruct @ libquassel.js:21658Quassel.dispatch @ libquassel.js:21849(anonymous function) @ libquassel.js:21960EventEmitter.emit @ libquassel.js:6810handleData @ libquassel.js:16756(anonymous function) @ libquassel.js:16722EventEmitter.emit @ libquassel.js:6810readableAddChunk @ libquassel.js:8231Readable.push @ libquassel.js:8190gotBuffer @ libquassel.js:20030(anonymous function) @ libquassel.js:20041

**Comment by magne4000** [comment]
you should update to 2.0. Unless there's something specific that doesn't allow you to do that ?

**Comment by rejinka** [comment]
Thanks, but i were not aware about 2.0. The only tagged version is 1.3 :-/

**Comment by magne4000** [comment]
You probably should stay on master branch, I delevop on dev one.
