### ISSUE TITLE
Ability to choose chat list

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#179]
It'd be nice to be able to choose which custom chat list that qusselweb uses to make it easier to have a list specifically for it.

**Comment by tecknojock** [comment]
While we're add it, if you add this, it probably also makes sense to be able to edit your chat lists.

**Comment by magne4000** [comment]
I created a second issue #187 for the ability to edit the chat lists

**Comment by magne4000** [comment]
![image](https://cloud.githubusercontent.com/assets/1098371/18871363/5356dee6-84b5-11e6-955e-31553dde1c22.png)
Implemented on `dev` branch for now, needs some testing because it uses a new version a `libquassel` with breaking changes.

**Comment by tecknojock** [comment]
I think this broke https://github.com/magne4000/quassel-webserver/issues/178 again. 

Also it doesnt remember which chat list you had last, which would be nice.

**Comment by magne4000** [comment]
Should be fine now
