### ISSUE TITLE
[Enhancement] - Unread messages/highlight and unread channel counters

### ISSUE THREAD

**Issue by DWSR** [magne4000/quassel-webserver#182]
It would be nice to have a (hidden) unread messages/highlight count and unread channel count exposed. Specifically this is for integration with Franz: https://github.com/meetfranz/plugins

**Comment by magne4000** [comment]
Just accessing it through javscript would be enough ? Or does it need to be a hidden DOM Element ?

**Comment by magne4000** [comment]
With this fix, the counter value is available at any time with:
```javascript
angular.element('*[ng-app]').injector().get('$favico').counter()
```
