### ISSUE TITLE
User list for channels no longer showing

### ISSUE THREAD

**Issue by nzrf** [magne4000/quassel-webserver#198]
For all of my network connections and channels. I am no longer showing active users in room. 
I am able to see the current user list with quasseldroid and Irssi w/quassel plugin. 

![screen shot 2016-10-10 at 8 12 59 am](https://cloud.githubusercontent.com/assets/4129944/19237219/66f67734-8ec1-11e6-8f59-e38b141b4db3.png)

**Comment by magne4000** [comment]
On what version of quassel-webserver are you ?
Is your `libquassel` up-to-date ? (have your run `npm update`)
Do you have any error in your browser's console ?

**Comment by nzrf** [comment]
quassel-core-0.12.4-1.el7.x86_64
node -v = v6.7.0 (I have run npm update -g and restarted the service.)
I have tried Safari Version 10.0 (12602.1.50.0.10)  and Chrome Version 53.0.2785.143 (64-bit)
Only errors I have are from Safari and those look to have an issue #160 tracking those.

git log has last commit of he following and I am running on master branch. 

commit f5702d8b3abbb38f6f62e1c9993097a6562f58d4
Merge: 92323b1 0b5dc13
Author: Joël Charles <joel.charles91@gmail.com>
Date:   Mon Oct 3 09:39:50 2016 +0200

    Merge pull request #194 from digitalcircuit/fix-doc-proxy-local

    Update README with note on --listen localhost

**Comment by magne4000** [comment]
Just to be sure did you also ran `npm update` without `-g` option ? Because it doesn't update the same packages.

**Comment by nzrf** [comment]
I did both again and restarted. Same problem. I will try and wipe the tree clone down again and put my setting back.

**Comment by nzrf** [comment]
No longer showing after just doing a clean install.
