### ISSUE TITLE
Allow listening via Unix socket to avoid DNS rebind attacks

### ISSUE THREAD

**Issue by digitalcircuit** [magne4000/quassel-webserver#201]
## In brief
- Allow specifying Unix domain sockets or Windows named pipes
  - Avoids DNS rebinding attacks where local server's exposed
  - `--port` handling logic will need to avoid forcing a port in this mode
  - Matters less given Quassel Web has authentication, but still a potential concern
- Update README to suggest using sockets/pipes when using a reverse proxy
## Rationale

Listening on `localhost` doesn't offer adequate isolation in several situations, as [evident with the recent Guile remote execution vulnerability](https://lwn.net/Articles/703485/).  Unix domain sockets offer a stronger form of isolation, avoiding requiring an extra port set aside, too.  PHP can already use this.  While [NodeJS supports Unix domain sockets](https://nodejs.org/api/net.html#net_server_listen_path_backlog_callback), it needs `server.listen` to be called without a port number.

Quassel Web should allow specifying a local socket for listening in situations when running behind a reverse-proxy.  While the attack surface is minimal as Quassel Web doesn't trust local connections, there's still potential risks of allowing HTTP access via other local accounts.  Ideally, the `README.md` should mention how to set local sockets up, too.

_Open for discussion, might try to work on this if you don't have the time.  Just didn't want to lose the details._

**Comment by scj643** [comment]
I can agree with this my python service runs on a Unix socket and is then proxied through Nginx.

**Comment by magne4000** [comment]
I'll probably need to switch from [express](http://expressjs.com/) to [hapi](http://hapijs.com/) for this to work. See expressjs/express#3107.

**Comment by magne4000** [comment]
It's now implemented in `dev` branch. Probably needs a little more testing before beeing merged into `master`. Also, I can't find a way to make it work with Apache (see http://www.gossamer-threads.com/lists/apache/users/459020). So if someone succeeds to do it, just post your solution here.

**Comment by digitalcircuit** [comment]
I'll try to test this soon; I'll need to research best practices for Unix socket locations and permissions.  Thanks for the quick response again!

**Comment by digitalcircuit** [comment]
Seems [this blog post on "Handling /var/run with systemd"](https://blog.hqcodeshop.fi/archives/93-Handling-varrun-with-systemd.html) is the way to go.

I've migrated my setup from running Quassel Web in ```tmux``` to a dedicated service that directly runs NodeJS.
```
# systemd unit file for Quassel Web
# Based on:  https://bbs.archlinux.org/viewtopic.php?id=148170
# And: https://blog.hqcodeshop.fi/archives/93-Handling-varrun-with-systemd.html
[Unit]
Description=Quassel Web server for web-based IRC chatting
After=local-fs.target network.target

[Service]
Type=simple
User=quassel-web
# Run ExecStartPre with root-permissions to create socket
# Directory creation and socket deletion can fail, but chown ownership is required
PermissionsStartOnly=true
ExecStartPre=-/bin/mkdir /var/run/quassel-web
ExecStartPre=/bin/chown -R quassel-web:quassel-web /var/run/quassel-web/
ExecStartPre=-/bin/rm /var/run/quassel-web/quassel-web.sock
# Run ExecStart with User/Group permissions above
ExecStart=/usr/bin/node "/home/quassel-web/quassel_web_root/qweb/quassel-webserver/app.js" --socket="/var/run/quassel-web/quassel-web.sock"

[Install]
WantedBy=multi-user.target
```

Everything seems to work!  At some point I'll try to clean up my scripts to make a general purpose guide for running Quassel Web as a dedicated, locked-down user.

Pardon the long delay, and thank you for your work in setting this up!
