### ISSUE TITLE
Stuck loading chats if no chat views defined (e.g. first run)

### ISSUE THREAD

**Issue by digitalcircuit** [magne4000/quassel-webserver#209]
## In brief
* Quassel Web doesn't set up any chat views when needed
  * Happens on first run if the desktop client is never connected
  * Desktop client defines an ```All Chats``` by default
  * Fixes one case of indefinite ```Loading``` spinner

## Test case
*Start from a clean Quassel core, identity configured,* **no networks defined** *and* **never touched by the Quassel desktop client**

1.  Go to settings cog → ```Networks```
2.  Click ```+``` to add a new network
3.  Fill out the details
    * E.g. ```chat.freenode.net``` for Host, leave Port unchanged, check ```Use encrypted connection```
4.  Click ```Save```

**Expected**
```New network``` shows up in chat list, allowing you to connect.

**Actual**
Chat list remains spinning indefinitely.

**Workaround**
Connect once with the Quassel desktop client, making no changes.  Reload Quassel Web.

**Comment by magne4000** [comment]
I need to add support for adding chat views in [libquassel](https://github.com/magne4000/libquassel).

**Comment by magne4000** [comment]
This one will probably need a little more testing before I merge into `master`.

**Comment by digitalcircuit** [comment]
With a fresh Quassel core + Quassel Webserver configured via SaltStack, I can confirm that ```master``` still fails to set up (as expected), but switching to ```dev```, restarting, and reconnecting added the All Chats view, allowing the interface to load.

Thank you!  If there's any more tests to do, let me know.
