### ISSUE TITLE
Not able to set an Apache reverse proxy

### ISSUE THREAD

**Issue by duramato** [magne4000/quassel-webserver#217]
I've followed the example in the readme and the virtual host is as follows:
```
<VirtualHost *:80>
ServerName domain
SSLProxyEngine On
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off

RewriteEngine on
RewriteRule /quassel/p/socket(.*) ws://IP_ADRESS:64443/quassel/p/socket$1 [P,L]
ProxyPass /quassel https://IP_ADRESS:64443/quassel

</VirtualHost>
```
everything seems to work except the "connect", which i believe is the websockets.

![image](https://pls.gtfo.accountant/sWxAT.png)

Don't know what i've done wrong, i did setup quasselwebser to  listen on /quassel

**Comment by magne4000** [comment]
Start `quassel-webserver` in HTTP instead of HTTPS, and replace (through config file or `-m http` option)
```apache
ProxyPass /quassel https://IP_ADRESS:64443/quassel
``` 
by
```apache
ProxyPass /quassel http://IP_ADRESS:64080/quassel
```

**Comment by duramato** [comment]
Same thing, i changed to:
![image](https://pls.gtfo.accountant/d7gUv.png)
![image](https://lol.doyou.bid/fTCzA.png)

quassel-webserver running on http mode and 64080 port

**Comment by magne4000** [comment]
No errors in browser's console or quassel-webserver console ?
Also, could you try from Firefox, I know that Chrome tends to now block some things if you are not in HTTPS.

**Comment by duramato** [comment]
I'm browsing on Firefox.
There is an error:

![image](https://pls.gtfo.accountant/gGqqm.png)

**Comment by magne4000** [comment]
There should also been a corresponding failed XHR call in Network tab, could you also paste a screenshot of that please ?

**Comment by duramato** [comment]
From what i see its the connect endpoint, it's this what you want? 

![image](https://pls.gtfo.accountant/3suVg.png)

**Comment by magne4000** [comment]
Seems that the `POST` request doesn't succeed.
You'll have some other checks to do:
- Check your apache logs to find a hint on `POST /quassel/p/connect`. Paste it here if there is something, otherwise that means that something on your computer (firewall ?) or network (firewall ?) is blocking the request.
- Check nodejs console logs to also see the same hit. If you don't see it, it means that something is wrong with Apache configuration.

**Comment by magne4000** [comment]
Some news on this ?

**Comment by magne4000** [comment]
Some news on this ?

**Comment by duramato** [comment]
Been busy IRL, I'll investigate tomorrow if it's ok

**Comment by magne4000** [comment]
Closing this, comment when you have some infos if it's still relevant

**Comment by pfoo** [comment]
I might be hitting the same issue. 
Proxy is working and loading the login page, but when trying to connect, apache is not receiving any request at all.

When loading the login page, Firefox console logs is showing this : 
`Firefox can't establish a connection to the server at wss://quassel.mydomain.tld/`

When clicking on the connect button : 
`Error: Unhandled error. (undefined)
o.prototype.emit@https://quassel.mydomain.tld/javascripts/libquassel.js:1:68414
v/this.onwrite/</<@https://quassel.mydomain.tld/javascripts/libquassel.js:1:153496
v/this.onwrite/<@https://quassel.mydomain.tld/javascripts/libquassel.js:1:153392
v/this.onwrite@https://quassel.mydomain.tld/javascripts/libquassel.js:1:153250
value@https://quassel.mydomain.tld/javascripts/libquassel.js:1:481311
C@https://quassel.mydomain.tld/javascripts/libquassel.js:1:154372
m.prototype.write/i<@https://quassel.mydomain.tld/javascripts/libquassel.js:1:157563
m.prototype.write@https://quassel.mydomain.tld/javascripts/libquassel.js:1:157075
setServer@https://quassel.mydomain.tld/javascripts/ng-quassel.js:64:9
$scope.login@https://quassel.mydomain.tld/javascripts/angular-controller.js:1252:9
fn@https://quassel.mydomain.tld/javascripts/angular.min.js line 237 > Function:4:132
e@https://quassel.mydomain.tld/javascripts/angular.min.js:282:195
$eval@https://quassel.mydomain.tld/javascripts/angular.min.js:147:309
$apply@https://quassel.mydomain.tld/javascripts/angular.min.js:148:12
compile/</<@https://quassel.mydomain.tld/javascripts/angular.min.js:282:245
dispatch@https://quassel.mydomain.tld/javascripts/jquery.min.js:3:10263
add/q.handle@https://quassel.mydomain.tld/javascripts/jquery.min.js:3:8325
angular.min.js:122:8 `

**Comment by igalic** [comment]
I've been dealing with this since last night again, after i managed to upgrade the containers running the different parts

the worst part: i've solved this before already, but didn't put it in my automation, so i don't remember how!

**Comment by pfoo** [comment]
It's not working since commit d47c04d1c8a81565c068a23981f657b69052a040

**Comment by igalic** [comment]
i may have identified the culprit 

https://github.com/magne4000/quassel-webserver/commit/d47c04d1c8a81565c068a23981f657b69052a040#diff-da99362f5448df30f93650819c1fdab3R72

**Comment by magne4000** [comment]
Copying my response here:
> Actually, if your proxy upgrade your server from HTTP to HTTPS, it must also upgrade WS to WSS. I'm currently using it behind a nginx proxy this way.

**Comment by igalic** [comment]
copying (rewording) my response here:

> does that mean if my frontend (apache httpd proxy) is running under TLS, i have to issue a valid (!!) certificate to my backend (quassel-webserver)?

**Comment by magne4000** [comment]
Not at all. a simple schema of what happens:
`QWS loaded in browser -> wss:// connection made to proxy -> proxy catches the connection and forward it to ws:// backend -> QWS server receives  the response`

**Comment by igalic** [comment]
yes, we have trouble with the second part:

```
Firefox can’t establish a connection to the server at wss://im.eena.me/.
```

**Comment by pfoo** [comment]
After some investigations : 
This is not working :
```
RewriteEngine On
RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule /p/socket(.*) ws://192.168.5.10:64080/p/socket$1 [P,L]
```

But this is :
```
RewriteEngine On
RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule /(.*) ws://192.168.5.10:64080/$1 [P,L]

```

Did the ws endpoint changed on the app side ?

**Comment by igalic** [comment]
reading

https://github.com/apache/httpd/blob/d26f2a1be6d9b34cac9a69d5c66601c10132f273/modules/proxy/mod_proxy_wstunnel.c#L471-L493

i believe we should simply be able to chain `ProxyPass` directives, rather than invoking `mod_rewrite`, since the entry into the module already does exactly what our `RewriteCond`s do.

i'll test my Hypothesis and report back (with a pull request)

**Comment by igalic** [comment]
nope, it's not possible, so i opened this issue: https://bz.apache.org/bugzilla/show_bug.cgi?id=63132

**Comment by pfoo** [comment]
Is there no more a specific url for the websocket part ? That would allow the use of ProxyPassMatch
