### ISSUE TITLE
Fails to scroll down

### ISSUE THREAD

**Issue by fish-face** [magne4000/quassel-webserver#219]
I have the frequent problem on recent Chrome and Firefox that quassel-webserver fails to scroll down when new messages arrive. This is a particular problem because of focus issues that mean scrolling with the mouse can be a bit anoying.

**Comment by magne4000** [comment]
Okay, I gave up doing this by myself :relaxed: ... I'm using this lib which seems to do a great work on that matter https://github.com/Luegg/angularjs-scroll-glue
