### ISSUE TITLE
quassel-webserver candidate snap fails to connect

### ISSUE THREAD

**Issue by elopio** [magne4000/quassel-webserver#220]
Hey @magne4000,

I'm trying the candidate snap, and it gets stuck during connection. The quassel-core log shows:

2017-01-13 13:32:59 Warning: "Socket error 13: Error during SSL handshake: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol" 
2017-01-13 13:32:59 Info: Non-authed client disconnected: 127.0.0.1 

Do you have any idea of what could be causing this?

I'm testing in Ubuntu 16.04.

```
$ snap list
Name               Version  Rev  Developer  Notes
core               16.04.1  714  canonical  -
quassel-webserver  master   10   magne4000  -
```

Here are the steps to reproduce: https://gist.github.com/elopio/e8a5214aa89a320ebd505b5dc184e2df

**Comment by magne4000** [comment]
After a quick test after installing the snap, with my existing quassel-core, I do not have this behavior. I'm searching where it can come from.

**Comment by magne4000** [comment]
It probably comes from a misconfiguration of quassel-core (outdated certificate perhaps ?).

**Comment by elopio** [comment]
Hey @magne4000, I'm back from vacations and ready to get quassel tested everywhere :)
I'm using a freshly installed ubuntu 16.04 vm, which gets me quassel-core 0.12.2-0ubuntu1.

When I install it with apt, I get this message: Generating SSL certificate as /var/lib/quassel/quasselCert.pem ...

I'm not really sure what to check here. How to check if the certificate is outdated?

**Comment by magne4000** [comment]
You can check certificate with this command `openssl x509 -in /var/lib/quassel/quasselCert.pem  -text -noout`.
I tried also with an empty quassel-core, as no error either on my side.

**Comment by elopio** [comment]
@magne4000 http://paste.ubuntu.com/23882979/
Seems correct, doesn't it?

quassel-webserver doesn't need to read that file, right?

**Comment by magne4000** [comment]
Quassel-webserver doesn't read this, but if it's invalid, there's a possibility that forge (the lib in charge of SSL browser side) could refuse it.

And yes, I'm using 16.04.

**Comment by Franderg** [comment]
I am trying the steps in link: https://gist.github.com/elopio/e8a5214aa89a320ebd505b5dc184e2df
Not problem to install Quassel webserver, but in the steps to create a account in the step number 4 then click to commit button, the page keep saying connecting and don't load the next step...

I'm using Ubuntu 16.04.01.

**Comment by magne4000** [comment]
I found how to reproduce the issue, I'm on it !

**Comment by magne4000** [comment]
I don't know how you trigger a `npm update` from a snap, but it will fix the issue.

**Comment by elopio** [comment]
@magne4000 nice work. I bumped the version of libquassel and it worked here :D

Thanks @Franderg for confirming the bug.
