### ISSUE TITLE
Ability to disable the hide/show button

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#226]
I keep accidentally hitting the show/hide hot button on the left of the channel. Could there be an option to just disable this feature and just use it through the dropdown menu, or toggle it back on when needed?

**Comment by tecknojock** [comment]
On top of that, It'd be nice if the default could be changed on the button from hide permanantly to hide temporarily.

**Comment by magne4000** [comment]
it shouldn't be triggered if icons are not visible

**Comment by tecknojock** [comment]
Then, I think, I'm encountering a bug of some sort.

**Comment by magne4000** [comment]
And that's why it's already fixed :smiley:

**Comment by tecknojock** [comment]
Perfect! Thanks! The email alerts unfortunately don't show comit info xP
