### ISSUE TITLE
batch $apply calls per packet

### ISSUE THREAD

**Issue by yorickvP** [magne4000/quassel-webserver#229]
This thing is already really fast. So I profiled it, and it turns out it's spending multiple seconds per `Quassel.handleStruct`, each containing dozens of $apply calls. I don't really know how Angular works at all, but I feel like this could be more efficient. I changed some on('bufferview.*') $apply calls to $applyAsync and shaved a few seconds from the connect time, but maybe it could be better still. (it now spends a few seconds running anonymous functions from somewhere instead).

**Comment by magne4000** [comment]
That's indeed a good place where I could made some optimizations.

**Comment by digitalcircuit** [comment]
Connect seems a lot faster now, awesome!

Unfortunately, some buffers now show up out of alphabetical order.  Perhaps the buffer sorting call gets run a bit too early/wrong timing?  I can open a new issue if desired; I'm not certain it's caused by this.

**Comment by magne4000** [comment]
I'll have a look, don't bother creating another issue for this

**Comment by tecknojock** [comment]
This is an issue I've had for a long time. Sometimes buffers get saved in a weird way, and I meant to make a report on it. The 'fix' is to hide and unhide all buffers on a server and then it'll be correct in the future. Not sure that these two are related.

**Comment by magne4000** [comment]
Yep, I just noticed that they are in wrong order in all clients ...

**Comment by magne4000** [comment]
Checking and unchecking "sort alphabetically" also fixes this (in official client) ... I will see if that's induced by webclient.

**Comment by tecknojock** [comment]
You get the same behavior in the official client too, because when you get new PMs and stuff it doesnt take into account hidden buffers for the alphabetical sorting.

**Comment by magne4000** [comment]
oh, ok. So closing discussion on that then.
