### ISSUE TITLE
Mobile devices: Context menus are unreachable with touch

### ISSUE THREAD

**Issue by TheOneRing** [magne4000/quassel-webserver#232]
Context menus are unreachable with touch.
Disabling the hover effect with touch might be sufficient.

**Comment by yorickvP** [comment]
Context menus work for me on a long press (chrome). What browser/platform?

**Comment by TheOneRing** [comment]
Yes but with a mouse they are indicated by the hover animation with touch the user has no idea that they have to long press an element of the list.
Also long press is not the most common way anymore, to open a context menu.

**Comment by magne4000** [comment]
The commit shoumd fix this behavior. Now, on mobile, context menu buttons will always be visible (before you could click on them but they were hidden). Long press still work.

**Comment by TheOneRing** [comment]
I'll test it as soon as I got my raspberry pi working again ..... (damned sd cards)
