### ISSUE TITLE
Autoremove socket when using systemd

### ISSUE THREAD

**Issue by scj643** [magne4000/quassel-webserver#243]
To remove a socket automatically when using systemd add 
`PIDFile=/path/to/socket.sock` under the `[Service]` section of `quassel-webserver.service`

**Comment by digitalcircuit** [comment]
That seems like it might be misusing the `PIDFile` feature.  According to [the systemd service documentation on `PIDFile`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#PIDFile= ), this file should contain the PID of the Quassel Webserver process, *not* an arbitrary file (*emphasis mine*):
> `PIDFile=`
> Takes an absolute file name pointing to the PID file of this daemon. Use of this option is recommended for services where `Type=` is set to `forking`. **systemd will read the PID of the main process of the daemon after start-up of the service**. systemd will not write to the file configured here, although it will remove the file after the service has shut down if it still exists. 

This might work happen to do what you want, but a better approach might be use [`ExecStopPost`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStopPost= ) as it's designed for this purpose (*emphasis mine*):
> `ExecStopPost=`
> Additional commands that are executed after the service is stopped. This includes cases where the commands configured in `ExecStop=` were used, where the service does not have any `ExecStop=` defined, or where the service exited unexpectedly. This argument takes multiple command lines, following the same scheme as described for `ExecStart=`. Use of these settings is optional. Specifier and environment variable substitution is supported. Note that – unlike `ExecStop=` – commands specified with this setting are invoked when a service failed to start up correctly and is shut down again.
>
> It is **recommended to use this setting for clean-up operations that shall be executed even when the service failed to start up correctly**. Commands configured with this setting need to be able to operate even if the service failed starting up half-way and left incompletely initialized data around. As the service's processes have been terminated already when the commands specified with this setting are executed they should not attempt to communicate with them.
>
> Note that all commands that are configured with this setting are invoked with the result code of the service, as well as the main process' exit code and status, set in the `$SERVICE_RESULT`, `$EXIT_CODE` and `$EXIT_STATUS` environment variables, see systemd.exec(5) for details.

You just need to mimic the `ExecStartPre` line with an `rm`, using `ExecStopPost=-rm ...` so failure is okay, akin to [the `ExecStartPre` here](https://github.com/digitalcircuit/salt-box-quassel/blob/18edeb5f1530f561a7d9df285c553cb36b1ad349/salt/files/quassel-web/quassel-web.service#L21 ).

> `ExecStopPost=-/bin/rm /var/run/quassel-web/quassel-web.sock`

*The `StopPost` is untested; I'll update my service file soon.*

**Comment by magne4000** [comment]
Added in `3.0`
