### ISSUE TITLE
'TLS error: Could not decrypt record or bad MAC' error in Chromium

### ISSUE THREAD

**Issue by rodneyrod** [magne4000/quassel-webserver#248]
On login, I keep getting this error now from my Chromium browser on Windows
If there's any further information you need, just let me know how to collect it and I'll post it as soon as I can.

**Comment by rodneyrod** [comment]
Just ran 'git pull && npm prune && npm update' and restarted the service, seems to have cleared up the issue.
Only thing that I could see updated though is 'pug@2.0.0-rc.1'

**Comment by magne4000** [comment]
duplicate #160
