### ISSUE TITLE
Client stays connected to core after use clicks "Logout" or closes browser tab

### ISSUE THREAD

**Issue by jakexks** [magne4000/quassel-webserver#25]
Steps to reproduce:
   1. Open the regular quassel client, check File -> Core Info
   2. Verify "Connected Clients" is 1.
   3. Log in to quassel-webserver, check connected clients has increased to 2.
   4. Press "Logout" or close the tab.
   5. Connected clients should go back to 1, but remains at 2 (you can keep increasing this by logging in again and again from quassel-webserver)
   6. Kill quassel-webserver and verify connected clients has returned to 1.

This is important if you use quassel's "set away when no clients are connected" feature.

**Comment by magne4000** [comment]
fixed in libquassel@0.2.1
