### ISSUE TITLE
Offer sign-in using GitHub

### ISSUE THREAD

**Issue by probonopd** [magne4000/quassel-webserver#255]
It would be cool if quassel-webserver could (optionally) offer this:

![Sign in with GitHub](https://user-images.githubusercontent.com/2480569/32992785-408f4cc4-cd4f-11e7-82a5-02409f575737.png)

One password less to remember and type!

**Comment by probonopd** [comment]
I was informed that the credentials used to sign-in to quassel-webserver are also used to connect to the Quassel core, so I fear this won't be easily feasible, hence closing.

**Comment by xNevo** [comment]
It's not possible unless quassel starts supporting OAuth.

**Comment by probonopd** [comment]
Unless you use the GitHub sign in only to sign the user into the web interface, where he can store the "real" credentials that are used to authenticate with Quassel. But storing credentials may be undesirable. Hence closed.
