### ISSUE TITLE
project does not build on node-10

### ISSUE THREAD

**Issue by igalic** [magne4000/quassel-webserver#267]
due to its current list of dependency versions, quassel-webserver cannot build on node v10, the current development latest release.

The errors occur because one function in [nan](https://github.com/nodejs/nan) is relying on a function that was deprecated in node v8.

I have no idea how to upgrade the dependencies myself, so i've [asked npm.community](https://npm.community/t/how-to-upgrade-a-project-to-node-10-which-has-nan-in-its-dependency-tree/1411)

**Comment by igalic** [comment]
https://github.com/magne4000/net-browserify/pull/1 this might help

**Comment by magne4000** [comment]
Fixed by `3.0`
