### ISSUE TITLE
Missing channels

### ISSUE THREAD

**Issue by needo37** [magne4000/quassel-webserver#274]
I have just setup quassel-web. I can login and connect to my quassel-core. The Networks are displayed as well as the settings but none of the channels are. I used https://hub.docker.com/r/bodsch/docker-quassel-web I was wondering if there was any thing I missed?

**Comment by ohnx** [comment]
Can you send a screenshot maybe? Make sure that the channels are not collapsed (click the arrow to the left of the network name). Otherwise, I'm not sure what could be causing the issue.

**Comment by needo37** [comment]
Thank you for the quick response. I have attached a screenshot as requested.

![quassel-web](https://user-images.githubusercontent.com/5664046/54081711-872bc680-42ce-11e9-9b4c-a9ae341c975d.PNG)

**Comment by ohnx** [comment]
Hmm, that's is strange, I'm not sure what's the problem here, unfortunately.

Can you try to see if there are any obvious error messages in the debug console?

**Comment by needo37** [comment]
I think it was a weird issue with the docker container. It updated today and is working correctly. Thank you.

**Comment by stevesoltys** [comment]
@ohnx @needo37 this issue occurs when you have a chat list and enable "hide inactive chats". Regardless of which chats you mark as inactive, they are all hidden.

**Comment by ohnx** [comment]
Sorry for my ignorance, but where is the "hide inactive chats" option found?

**Comment by stevesoltys** [comment]
It's on the core side in settings under "Chat lists". You need to enable it via the regular Quassel client or Quasseldroid.
