### ISSUE TITLE
n is not a function error

### ISSUE THREAD

**Issue by infecticide** [magne4000/quassel-webserver#275]
I have pulled the latest code as of yesterday and verified my Apache config but I get the following errors when connecting to the Core:
```
Connecting to quasselcore
libquassel.js:8 Uncaught TypeError: n is not a function
    at C (libquassel.js:8)
    at libquassel.js:8
    at onwrite (libquassel.js:8)
    at C (libquassel.js:8)
    at libquassel.js:8
    at d.run (libquassel.js:8)
    at p (libquassel.js:8)
C @ libquassel.js:8
(anonymous) @ libquassel.js:8
onwrite @ libquassel.js:8
C @ libquassel.js:8
(anonymous) @ libquassel.js:8
d.run @ libquassel.js:8
p @ libquassel.js:8
setTimeout (async)
o @ libquassel.js:8
i.nextTick @ libquassel.js:8
nextTick @ libquassel.js:8
(anonymous) @ libquassel.js:8
onwrite @ libquassel.js:8
value @ libquassel.js:8
b @ libquassel.js:8
(anonymous) @ libquassel.js:8
m.write @ libquassel.js:8
(anonymous) @ libquassel.js:8
(anonymous) @ libquassel.js:8
o.emit @ libquassel.js:8
n.socket.onopen @ libquassel.js:8
libquassel.js:8 Uncaught TypeError: n is not a function
    at C (libquassel.js:8)
    at libquassel.js:8
    at onwrite (libquassel.js:8)
    at C (libquassel.js:8)
    at libquassel.js:8
    at d.run (libquassel.js:8)
    at p (libquassel.js:8)
    at h (libquassel.js:8)
C @ libquassel.js:8
(anonymous) @ libquassel.js:8
onwrite @ libquassel.js:8
C @ libquassel.js:8
(anonymous) @ libquassel.js:8
d.run @ libquassel.js:8
p @ libquassel.js:8
h @ libquassel.js:8
setTimeout (async)
o @ libquassel.js:8
p @ libquassel.js:8
setTimeout (async)
o @ libquassel.js:8
i.nextTick @ libquassel.js:8
nextTick @ libquassel.js:8
(anonymous) @ libquassel.js:8
onwrite @ libquassel.js:8
value @ libquassel.js:8
b @ libquassel.js:8
(anonymous) @ libquassel.js:8
m.write @ libquassel.js:8
(anonymous) @ libquassel.js:8
(anonymous) @ libquassel.js:8
o.emit @ libquassel.js:8
n.socket.onopen @ libquassel.js:8
angular-controller.js:1149 Logged in
angular-controller.js:1092 ERROR {message: "Could not decrypt record or bad MAC.", send: true, alert: {…}, origin: "client", toString: ƒ}
```

I can see the header and a "Loading" spinner in the left pane but no Networks or Channels are listed.

I have QuasselWeb configured as HTTP on port 64080 and Apache is proxying it to TLS to the outside world.

I was getting these TLS errors with an older version of QuasselWeb and was hoping it had been fixed.

The old version would eventually connect if I retried enough times but it was getting worse as time goes on.

**Comment by infecticide** [comment]
I should have also mentioned the following:

OS: Ubuntu 18.04

npm list:

quassel-webserver@3.0.1 /var/lib/quassel/quassel-webserver
+-- body-parser@1.18.3
| +-- bytes@3.0.0
| +-- content-type@1.0.4
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- depd@1.1.2
| +-- http-errors@1.6.3
| | +-- inherits@2.0.3
| | `-- statuses@1.5.0
| +-- iconv-lite@0.4.23
| | `-- safer-buffer@2.1.2
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- qs@6.5.2
| +-- raw-body@2.3.3
| | `-- unpipe@1.0.0
| `-- type-is@1.6.16
|   +-- media-typer@0.3.0
|   `-- mime-types@2.1.22
|     `-- mime-db@1.38.0
+-- commander@2.19.0
+-- cookie-parser@1.4.4
| +-- cookie@0.3.1
| `-- cookie-signature@1.0.6
+-- express@4.16.4
| +-- accepts@1.3.5
| | `-- negotiator@0.6.1
| +-- array-flatten@1.1.1
| +-- content-disposition@0.5.2
| +-- encodeurl@1.0.2
| +-- escape-html@1.0.3
| +-- etag@1.8.1
| +-- finalhandler@1.1.1
| | `-- statuses@1.4.0
| +-- fresh@0.5.2
| +-- merge-descriptors@1.0.1
| +-- methods@1.1.2
| +-- parseurl@1.3.2
| +-- path-to-regexp@0.1.7
| +-- proxy-addr@2.0.4
| | +-- forwarded@0.1.2
| | `-- ipaddr.js@1.8.0
| +-- range-parser@1.2.0
| +-- safe-buffer@5.1.2
| +-- send@0.16.2
| | +-- destroy@1.0.4
| | `-- statuses@1.4.0
| +-- serve-static@1.13.2
| +-- setprototypeof@1.1.0
| +-- statuses@1.4.0
| +-- utils-merge@1.0.1
| `-- vary@1.1.2
+-- httpolyglot@0.1.2
+-- less@3.9.0
| +-- clone@2.1.2
| +-- errno@0.1.7
| | `-- prr@1.0.1
| +-- graceful-fs@4.1.15
| +-- image-size@0.5.5
| +-- mime@1.4.1
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- promise@7.3.1
| | `-- asap@2.0.6
| +-- request@2.88.0
| | +-- aws-sign2@0.7.0
| | +-- aws4@1.8.0
| | +-- caseless@0.12.0
| | +-- combined-stream@1.0.7
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.2
| | +-- forever-agent@0.6.1
| | +-- form-data@2.3.3
| | | `-- asynckit@0.4.0
| | +-- har-validator@5.1.3
| | | +-- ajv@6.10.0
| | | | +-- fast-deep-equal@2.0.1
| | | | +-- fast-json-stable-stringify@2.0.0
| | | | +-- json-schema-traverse@0.4.1
| | | | `-- uri-js@4.2.2
| | | |   `-- punycode@2.1.1
| | | `-- har-schema@2.0.0
| | +-- http-signature@1.2.0
| | | +-- assert-plus@1.0.0
| | | +-- jsprim@1.4.1
| | | | +-- extsprintf@1.3.0
| | | | +-- json-schema@0.2.3
| | | | `-- verror@1.10.0
| | | `-- sshpk@1.16.1
| | |   +-- asn1@0.2.4
| | |   +-- bcrypt-pbkdf@1.0.2
| | |   +-- dashdash@1.14.1
| | |   +-- ecc-jsbn@0.1.2
| | |   +-- getpass@0.1.7
| | |   +-- jsbn@0.1.1
| | |   `-- tweetnacl@0.14.5
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- oauth-sign@0.9.0
| | +-- performance-now@2.1.0
| | +-- tough-cookie@2.4.3
| | | +-- psl@1.1.31
| | | `-- punycode@1.4.1
| | +-- tunnel-agent@0.6.0
| | `-- uuid@3.3.2
| `-- source-map@0.6.1
+-- less-middleware@3.1.0
| `-- node.extend@2.0.2
|   +-- has@1.0.3
|   | `-- function-bind@1.1.1
|   `-- is@3.3.0
+-- libquassel@3.1.5
| +-- debug@4.1.1
| | `-- ms@2.1.1
| +-- node-forge@0.7.6
| `-- qtdatastream@1.1.0
|   +-- debug@4.1.1
|   | `-- ms@2.1.1
|   `-- int64-buffer@0.99.1007
+-- morgan@1.9.1
| +-- basic-auth@2.0.1
| `-- on-headers@1.0.2
+-- nodemon@1.18.10
| +-- chokidar@2.1.2
| | +-- anymatch@2.0.0
| | | +-- micromatch@3.1.10
| | | | +-- arr-diff@4.0.0
| | | | +-- define-property@2.0.2
| | | | | `-- is-descriptor@1.0.2
| | | | |   +-- is-accessor-descriptor@1.0.0
| | | | |   +-- is-data-descriptor@1.0.0
| | | | |   `-- kind-of@6.0.2
| | | | +-- extend-shallow@3.0.2
| | | | | +-- assign-symbols@1.0.0
| | | | | `-- is-extendable@1.0.1
| | | | |   `-- is-plain-object@2.0.4
| | | | +-- extglob@2.0.4
| | | | | +-- define-property@1.0.0
| | | | | | `-- is-descriptor@1.0.2
| | | | | |   +-- is-accessor-descriptor@1.0.0
| | | | | |   +-- is-data-descriptor@1.0.0
| | | | | |   `-- kind-of@6.0.2
| | | | | +-- expand-brackets@2.1.4
| | | | | | +-- define-property@0.2.5
| | | | | | +-- extend-shallow@2.0.1
| | | | | | `-- posix-character-classes@0.1.1
| | | | | `-- extend-shallow@2.0.1
| | | | +-- fragment-cache@0.2.1
| | | | +-- kind-of@6.0.2
| | | | +-- nanomatch@1.2.13
| | | | | +-- is-windows@1.0.2
| | | | | `-- kind-of@6.0.2
| | | | +-- object.pick@1.3.0
| | | | `-- regex-not@1.0.2
| | | `-- normalize-path@2.1.1
| | |   `-- remove-trailing-separator@1.1.0
| | +-- async-each@1.0.1
| | +-- braces@2.3.2
| | | +-- arr-flatten@1.1.0
| | | +-- array-unique@0.3.2
| | | +-- extend-shallow@2.0.1
| | | | `-- is-extendable@0.1.1
| | | +-- fill-range@4.0.0
| | | | +-- extend-shallow@2.0.1
| | | | +-- is-number@3.0.0
| | | | | `-- kind-of@3.2.2
| | | | |   `-- is-buffer@1.1.6
| | | | +-- repeat-string@1.6.1
| | | | `-- to-regex-range@2.1.1
| | | +-- isobject@3.0.1
| | | +-- repeat-element@1.1.3
| | | +-- snapdragon@0.8.2
| | | | +-- base@0.11.2
| | | | | +-- cache-base@1.0.1
| | | | | | +-- collection-visit@1.0.0
| | | | | | | +-- map-visit@1.0.0
| | | | | | | `-- object-visit@1.0.1
| | | | | | +-- get-value@2.0.6
| | | | | | +-- has-value@1.0.0
| | | | | | | `-- has-values@1.0.0
| | | | | | |   `-- kind-of@4.0.0
| | | | | | +-- set-value@2.0.0
| | | | | | | `-- extend-shallow@2.0.1
| | | | | | +-- to-object-path@0.3.0
| | | | | | +-- union-value@1.0.0
| | | | | | | `-- set-value@0.4.3
| | | | | | |   `-- extend-shallow@2.0.1
| | | | | | `-- unset-value@1.0.0
| | | | | |   `-- has-value@0.3.1
| | | | | |     +-- has-values@0.1.4
| | | | | |     `-- isobject@2.1.0
| | | | | +-- class-utils@0.3.6
| | | | | | +-- arr-union@3.1.0
| | | | | | +-- define-property@0.2.5
| | | | | | `-- static-extend@0.1.2
| | | | | |   +-- define-property@0.2.5
| | | | | |   `-- object-copy@0.1.0
| | | | | |     +-- copy-descriptor@0.1.1
| | | | | |     `-- define-property@0.2.5
| | | | | +-- component-emitter@1.2.1
| | | | | +-- define-property@1.0.0
| | | | | | `-- is-descriptor@1.0.2
| | | | | |   +-- is-accessor-descriptor@1.0.0
| | | | | |   +-- is-data-descriptor@1.0.0
| | | | | |   `-- kind-of@6.0.2
| | | | | +-- mixin-deep@1.3.1
| | | | | | +-- for-in@1.0.2
| | | | | | `-- is-extendable@1.0.1
| | | | | `-- pascalcase@0.1.1
| | | | +-- define-property@0.2.5
| | | | | `-- is-descriptor@0.1.6
| | | | |   +-- is-accessor-descriptor@0.1.6
| | | | |   +-- is-data-descriptor@0.1.4
| | | | |   `-- kind-of@5.1.0
| | | | +-- extend-shallow@2.0.1
| | | | +-- map-cache@0.2.2
| | | | +-- source-map@0.5.7
| | | | +-- source-map-resolve@0.5.2
| | | | | +-- atob@2.1.2
| | | | | +-- decode-uri-component@0.2.0
| | | | | +-- resolve-url@0.2.1
| | | | | +-- source-map-url@0.4.0
| | | | | `-- urix@0.1.0
| | | | `-- use@3.1.1
| | | +-- snapdragon-node@2.1.1
| | | | +-- define-property@1.0.0
| | | | | `-- is-descriptor@1.0.2
| | | | |   +-- is-accessor-descriptor@1.0.0
| | | | |   +-- is-data-descriptor@1.0.0
| | | | |   `-- kind-of@6.0.2
| | | | `-- snapdragon-util@3.0.1
| | | +-- split-string@3.1.0
| | | `-- to-regex@3.0.2
| | |   `-- safe-regex@1.1.0
| | |     `-- ret@0.1.15
| | +-- UNMET OPTIONAL DEPENDENCY fsevents@^1.2.7
| | +-- glob-parent@3.1.0
| | | +-- is-glob@3.1.0
| | | `-- path-dirname@1.0.2
| | +-- is-binary-path@1.0.1
| | | `-- binary-extensions@1.13.0
| | +-- is-glob@4.0.0
| | | `-- is-extglob@2.1.1
| | +-- normalize-path@3.0.0
| | +-- path-is-absolute@1.0.1
| | +-- readdirp@2.2.1
| | | `-- readable-stream@2.3.6
| | |   +-- core-util-is@1.0.2
| | |   +-- isarray@1.0.0
| | |   +-- process-nextick-args@2.0.0
| | |   +-- string_decoder@1.1.1
| | |   `-- util-deprecate@1.0.2
| | `-- upath@1.1.2
| +-- debug@3.2.6
| | `-- ms@2.1.1
| +-- ignore-by-default@1.0.1
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.11
| |   +-- balanced-match@1.0.0
| |   `-- concat-map@0.0.1
| +-- pstree.remy@1.1.6
| +-- semver@5.6.0
| +-- supports-color@5.5.0
| | `-- has-flag@3.0.0
| +-- touch@3.1.0
| | `-- nopt@1.0.10
| |   `-- abbrev@1.1.1
| +-- undefsafe@2.0.2
| `-- update-notifier@2.5.0
|   +-- boxen@1.3.0
|   | +-- ansi-align@2.0.0
|   | +-- camelcase@4.1.0
|   | +-- cli-boxes@1.0.0
|   | +-- string-width@2.1.1
|   | | +-- is-fullwidth-code-point@2.0.0
|   | | `-- strip-ansi@4.0.0
|   | |   `-- ansi-regex@3.0.0
|   | +-- term-size@1.2.0
|   | | `-- execa@0.7.0
|   | |   +-- cross-spawn@5.1.0
|   | |   | +-- lru-cache@4.1.5
|   | |   | | +-- pseudomap@1.0.2
|   | |   | | `-- yallist@2.1.2
|   | |   | +-- shebang-command@1.2.0
|   | |   | | `-- shebang-regex@1.0.0
|   | |   | `-- which@1.3.1
|   | |   |   `-- isexe@2.0.0
|   | |   +-- get-stream@3.0.0
|   | |   +-- is-stream@1.1.0
|   | |   +-- npm-run-path@2.0.2
|   | |   | `-- path-key@2.0.1
|   | |   +-- p-finally@1.0.0
|   | |   `-- strip-eof@1.0.0
|   | `-- widest-line@2.0.1
|   +-- chalk@2.4.2
|   | +-- ansi-styles@3.2.1
|   | | `-- color-convert@1.9.3
|   | |   `-- color-name@1.1.3
|   | `-- escape-string-regexp@1.0.5
|   +-- configstore@3.1.2
|   | +-- dot-prop@4.2.0
|   | | `-- is-obj@1.0.1
|   | +-- make-dir@1.3.0
|   | | `-- pify@3.0.0
|   | +-- unique-string@1.0.0
|   | | `-- crypto-random-string@1.0.0
|   | `-- write-file-atomic@2.4.2
|   |   +-- imurmurhash@0.1.4
|   |   `-- signal-exit@3.0.2
|   +-- import-lazy@2.1.0
|   +-- is-ci@1.2.1
|   | `-- ci-info@1.6.0
|   +-- is-installed-globally@0.1.0
|   | +-- global-dirs@0.1.1
|   | | `-- ini@1.3.5
|   | `-- is-path-inside@1.0.1
|   |   `-- path-is-inside@1.0.2
|   +-- is-npm@1.0.0
|   +-- latest-version@3.1.0
|   | `-- package-json@4.0.1
|   |   +-- got@6.7.1
|   |   | +-- create-error-class@3.0.2
|   |   | | `-- capture-stack-trace@1.0.1
|   |   | +-- duplexer3@0.1.4
|   |   | +-- is-redirect@1.0.0
|   |   | +-- is-retry-allowed@1.1.0
|   |   | +-- lowercase-keys@1.0.1
|   |   | +-- timed-out@4.0.1
|   |   | +-- unzip-response@2.0.1
|   |   | `-- url-parse-lax@1.0.0
|   |   |   `-- prepend-http@1.0.4
|   |   +-- registry-auth-token@3.3.2
|   |   | `-- rc@1.2.8
|   |   |   +-- deep-extend@0.6.0
|   |   |   +-- minimist@1.2.0
|   |   |   `-- strip-json-comments@2.0.1
|   |   `-- registry-url@3.1.0
|   +-- semver-diff@2.1.0
|   `-- xdg-basedir@3.0.0
+-- pug@2.0.3
| +-- pug-code-gen@2.0.1
| | +-- constantinople@3.1.2
| | | +-- @types/babel-types@7.0.6
| | | +-- @types/babylon@6.16.5
| | | +-- babel-types@6.26.0
| | | | +-- babel-runtime@6.26.0
| | | | | +-- core-js@2.6.5
| | | | | `-- regenerator-runtime@0.11.1
| | | | +-- esutils@2.0.2
| | | | +-- lodash@4.17.11
| | | | `-- to-fast-properties@1.0.3
| | | `-- babylon@6.18.0
| | +-- doctypes@1.1.0
| | +-- js-stringify@1.0.2
| | +-- pug-attrs@2.0.3
| | +-- pug-error@1.3.2
| | +-- void-elements@2.0.1
| | `-- with@5.1.1
| |   +-- acorn@3.3.0
| |   `-- acorn-globals@3.1.0
| |     `-- acorn@4.0.13
| +-- pug-filters@3.1.0
| | +-- clean-css@4.2.1
| | +-- jstransformer@1.0.0
| | | `-- is-promise@2.1.0
| | +-- pug-walk@1.1.7
| | +-- resolve@1.10.0
| | | `-- path-parse@1.0.6
| | `-- uglify-js@2.8.29
| |   +-- source-map@0.5.7
| |   +-- uglify-to-browserify@1.0.2
| |   `-- yargs@3.10.0
| |     +-- camelcase@1.2.1
| |     +-- cliui@2.1.0
| |     | +-- center-align@0.1.3
| |     | | +-- align-text@0.1.4
| |     | | | `-- longest@1.0.1
| |     | | `-- lazy-cache@1.0.4
| |     | +-- right-align@0.1.3
| |     | `-- wordwrap@0.0.2
| |     +-- decamelize@1.2.0
| |     `-- window-size@0.1.0
| +-- pug-lexer@4.0.0
| | +-- character-parser@2.2.0
| | | `-- is-regex@1.0.4
| | `-- is-expression@3.0.0
| |   `-- acorn@4.0.13
| +-- pug-linker@3.0.5
| +-- pug-load@2.0.11
| | `-- object-assign@4.1.1
| +-- pug-parser@5.0.0
| | `-- token-stream@0.0.1
| +-- pug-runtime@2.0.4
| `-- pug-strip-comments@1.0.3
+-- serve-favicon@2.5.0
| +-- ms@2.1.1
| `-- safe-buffer@5.1.1
+-- untildify@3.0.3
`-- ws@6.2.0
  `-- async-limiter@1.0.0

**Comment by RealKelsar** [comment]
Same Problem here, but I atleast see the Networks.

**Comment by RealKelsar** [comment]
Ok, the error is gone, if don't hit a forced reload, but still no channels.

**Comment by magne4000** [comment]
@infecticide Can you just try to reload before trying to connect. The websocket seems to have closed. I need to fix that, but you can probably just have it working by just refreshing the page before login.
