### ISSUE TITLE
Cannot connect to core

### ISSUE THREAD

**Issue by maxxer** [magne4000/quassel-webserver#28]
I've just set up quassel on my vps, it works fine with quassel qt client, but it does not with quassel-webserver.
I reach login page, enter credentials, but then nothing at all happens.

All I get in quassel.log is this:

    2015-03-18 17:31:38 Info: Client connected from ::FFFF:A2FD:9A73%0 

Then if I reload the web page I get this additional info:

    2015-03-18 17:31:22 Warning: "Socket error 1: The remote host closed the connection"  
    2015-03-18 17:31:22 Info: Non-authed client disconnected: ::FFFF:A2FD:9A73%0 

But nothing else... Is there any log I can check to see what is going on? thanks

**Comment by magne4000** [comment]
Try to launch quassel-webserver like this :
```
DEBUG=quassel-webserver,libquassel:*,qtdatastream:* npm start
```
It will print debug information.

**Comment by maxxer** [comment]
After pressing *Connect* I see just this in the debug console:

     libquassel:main Using SSL +46s
     libquassel:main Sending client informations +4ms

Nothing more...
Could it be related to the fact that I have ipv6 enabled on this host? Or is there any special firewall rule, except core port and web port? As I said above the qt client connects fine from outside. thanks

**Comment by magne4000** [comment]
The core receives data (or you wouldn't have logs on the core), so i don't think that it is related to IPv6 or firewall.
It's probably related to the way i implemented the QDataStream protocol.
You can have a lot more debug info by setting this environment variable ```QTDSDEBUG=ON``` and relaunch quassel-webserver.

**Comment by maxxer** [comment]
Sorry but I see no changes in the log... Just the same output. 
Could it be related to special characters into the password, like *!"£$* ?
If you're in IRC my nick is *maxxer*

**Comment by magne4000** [comment]
Problem solved, it was nodejs version that was too old
