### ISSUE TITLE
Reducin lag

### ISSUE THREAD

**Issue by Zren** [magne4000/quassel-webserver#30]
For some reason, the client is using an entire core for nearly every operation.

I tried upping the [10ms debouce during on('change')](https://github.com/magne4000/quassel-webserver/blob/master/public/javascripts/angular-controller.js#L53) to 100ms, but it was still pretty laggy.

Commenting out [the else entire section](https://github.com/magne4000/quassel-webserver/blob/master/public/javascripts/angular-controller.js#L47-L53) however had a noticeable speed difference.

**Comment by magne4000** [comment]
Should be fixed by 76f4f216c74995fdecb43b427df0b933b557ee3e

**Comment by Zren** [comment]
For posterity sake, here's the side by tests I posted in IRC: https://giant.gfycat.com/HopefulScaryAlleycat.webm

https://github.com/magne4000/quassel-webserver/commit/76f4f216c74995fdecb43b427df0b933b557ee3e is much snappier.

**Comment by magne4000** [comment]
So we can consider this as closed ?
