### ISSUE TITLE
Disconnected Networks after init are shown as collapsed when they aren't.

### ISSUE THREAD

**Issue by Zren** [magne4000/quassel-webserver#34]
![quassel-disconnectednetworks](https://cloud.githubusercontent.com/assets/416367/6932012/e9f6dcac-d7e1-11e4-8783-7da31f446728.gif)

Also why not toggle a class: eg: `.network-channels.collapse`?

**Comment by magne4000** [comment]
I don't think that toggling a class is really a question here :) just a matter of preference on my side.
But still need to fix the issue ...

**Comment by Zren** [comment]
The fix didn't completely work. The first click will add the `expanded` class instead of closing (it was dynamically added with ng-class before). The fix is to add the `.expanded` like so:
```jade
span.collapsable.expanded(toggle="{{network.networkName}}-channels")
```
