### ISSUE TITLE
Redirect http:// to https:// when using https.

### ISSUE THREAD

**Issue by Zren** [magne4000/quassel-webserver#36]

**Comment by magne4000** [comment]
As we use custom ports for http and https, redirecting is not as natural as if we were using defaults port.
#### Use case with default ports:
http://localhost -> https://localhost
#### Use case with custom ports:
http://localhost:64080 -> https://localhost:64443

So it would require the user to purposely go on a port not specified by the output of the application.

**Comment by Orbixx** [comment]
Run nginx with a redirect?

**Comment by magne4000** [comment]
That's what I would recommend yes, it should be the role of a reverse proxy.
