### ISSUE TITLE
Support for binding to localhost

### ISSUE THREAD

**Issue by Orbixx** [magne4000/quassel-webserver#40]
I cannot see support for binding to localhost.

I'd like to use my local httpd to proxy https://myhost/quassel -> http://myhostlocalhost:64080 or whatever port

**Comment by magne4000** [comment]
By default it binds on all addresses, so also on localhost.

**Comment by magne4000** [comment]
You can also bind only to localhost by settings the environment variable `HOST` to `localhost`
```
HOST=localhost node app.js -m http
```
You would also need to set `prefixpath: 'quassel'` setting in `settings-user.js` in order to have
`https://myhost/quassel` -> `http://localhost:64080/quassel`

**Comment by Orbixx** [comment]
Sorted :)
