### ISSUE TITLE
Messages Out of Order

### ISSUE THREAD

**Issue by tinnvec** [magne4000/quassel-webserver#41]
Messages come in in the right order, but get reshuffled every so often and end up out of order, example:

>16:18:44	GPEG	http://www.history.com/interactives/witness-to-911
>16:18:26	icu	Jiro Loves Sushi
>16:18:38	DarkRedeemer	tinnvec, but what if the devil doesn't like it?
>16:18:42	testcom	chrismas: no
>16:21:11	<--	robert_ has quit
>16:19:09	chrismas	so there's no live streaming option for HBO now?
>16:19:00	GPEG	sad but riveting
>16:18:52	GPEG	Great Doc with no narration
>16:18:58	tinnvec	good lord, DarkRedeemer, you remember way more of the song than I do
>16:21:33	Tensorguy	i love the f111
>16:19:41	<--	mobile_1560 has quit
>16:19:12	testcom	so did Netflix posted an april fools day joke a week late? https://www.youtube.com/watch?v=NK33GjwzNRI&ab_channel=Netflix
>16:19:38	chrismas	how about that'

EDIT: this started happening after updating today

**Comment by magne4000** [comment]
Can you tell me if this fixes the issue ? Because i'm unable to reproduce the bug.

**Comment by tinnvec** [comment]
I'm still experiencing the same bug, perhaps I can elaborate on what I see:

I was on my laptop last night on the mac quassel client and everything was normal. When I look back at that time in the web client, the messages are severely out of order, it seems to get worse the farther I go back, sometimes hours of difference.

Watching it happen live, it looks like when a new message comes in is when things get wonky. The existing messages visibly jump up in the list. I'm not sure if it means anything, but a message is never moved forward in time (in regards to the messages order) always backwards. I'll see if I can do a screen recording or something to show it in action.

Hope that helps some!

**Comment by magne4000** [comment]
That's some weird behavior you have. I'll try to reproduce it on my side

**Comment by tinnvec** [comment]
I was able to record a 5 minute clip for you, hopefully the resolution is okay: https://drive.google.com/file/d/0B2tKMa3V6dkkQkpRN1BGTG85czg/view?usp=sharing

**Comment by magne4000** [comment]
My sort function was wrong ... I think this time it should be OK

**Comment by tinnvec** [comment]
Looks really good after the update, you are SUPER on top of things, thanks!
