### ISSUE TITLE
On message reply, chat pane does not scroll to latest message despite already sitting on the latest message

### ISSUE THREAD

**Issue by Orbixx** [magne4000/quassel-webserver#46]
As per subject, can you reproduce?

**Comment by magne4000** [comment]
It sometimes happens when the client receives 2 messages at the same time, or when the message is quite long.
I did not yet found a elegant solution to fix that :disappointed:

**Comment by magne4000** [comment]
It seems to do the trick for me. I'm closing this for now. If it happens again, don't hesitate to reopen it.

**Comment by Orbixx** [comment]
Thank you, I'll test later!
