### ISSUE TITLE
Current master (commit 997c984988) broken

### ISSUE THREAD

**Issue by Orbixx** [magne4000/quassel-webserver#50]
The login page for the current master seems broken, cleared cache and hard refreshed and the form no longer displays and the settings button does not seem to function.

**Comment by magne4000** [comment]
Can you open the javascript console and paste here the output ?

**Comment by Orbixx** [comment]
![screenshot 2015-04-30 at 15 29 16](https://cloud.githubusercontent.com/assets/1606867/7414948/b9d7da66-ef4d-11e4-9f3e-59f2cb214237.png)

**Comment by magne4000** [comment]
Did you do a `npm update` ?

**Comment by Orbixx** [comment]
I did not, I used nvm to install node 0.12.2 and execute the app.js

**Comment by magne4000** [comment]
Then you should, you need to update dependencies (in your case, [libquassel](http://www.github.com/magne4000/node-libquassel) is not up to date), as stated here : https://github.com/magne4000/quassel-webserver#on-the-server

**Comment by Orbixx** [comment]
Aha, sorry!

  nvm exec 0.12.2 npm update

Seemed to work! Thanks!
