### ISSUE TITLE
Hard word break on long words

### ISSUE THREAD

**Issue by tinnvec** [magne4000/quassel-webserver#53]
This may be a personal gripe of mine, and by no means a bug, but when a particularly long string of characters (often a url) is displayed, it causes the main chat area to gain a horizontal scrollbar.

Not a huge issue, except that from that point on, normal sentences no longer wrap correctly, expanding to the (now larger) full width of the main chat area. Due to keeping track of messages, the only way to fix it is to reload the page and reconnect.

if the css property word-wrap is set to break-word, it would keep everything in the original width, though I'm unsure how this would affect the click-ability of links (might even be browser dependent).

Thanks for all your hard work, it's been a great app to use!

**Comment by magne4000** [comment]
Could you add a screenshot please ? Because i'm unable to reproduce

**Comment by tinnvec** [comment]
Absolutely, it is below. The twitter link is the one that appears to be the culprit in this instance.

![screenshot 2015-05-12 11 44 12](https://cloud.githubusercontent.com/assets/757297/7593031/bd547be2-f89c-11e4-9707-f4861ce1ad29.png)

I did a little tinkering in element inspector and looks like word-wrap: break-word is already set on those backlog messages (.backlog .message). There's another property that does similar, word-break. Setting it to break-all will break mid-word no matter what and break-word will do it's best to make the breaks at word endings but also strictly breaks at the width if all else fails (in urls, it'll often break at the / ). Speaking of urls, looks like it wouldn't break them, in chrome at least.

**Comment by magne4000** [comment]
Can you tell me if this fixes your specific case ?
On my side it seems to work fine.

**Comment by tinnvec** [comment]
Works beautifully, thank you! I may have to whip you up a third theme as a token of my appreciation
