### ISSUE TITLE
'undefined is not a function'

### ISSUE THREAD

**Issue by disconsented** [magne4000/quassel-webserver#56]
https://gist.github.com/disconsented/501204c963153f0265f3
{'quassel-webserver': '0.1.2',
  npm: '2.9.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.3',
  openssl: '1.0.1m',
  uv: '1.5.0',
  v8: '3.28.71.19',
  zlib: '1.2.8' 

Running on Debian 8

**Comment by magne4000** [comment]
Can I have a dump of `npm list` ?

**Comment by disconsented** [comment]
https://gist.github.com/disconsented/2a6df9ce4adee297d23c
Is there a fast way to install all of those dependencies?

**Comment by magne4000** [comment]
hum, try removing your `node_modules` folder `rm -fr node_modules`, then reinstall all dependencies `npm install`. I think that will fix your issue.

**Comment by disconsented** [comment]
https://gist.github.com/disconsented/16be3ffa25f3fd586756
I assume the killed at the very bottom is a  bad thing but I do not see an error

**Comment by magne4000** [comment]
And you still have the error ? If so, can you post your new `npm list` please

**Comment by disconsented** [comment]
http://pastebin.com/PJHWHbL7

**Comment by magne4000** [comment]
You probably have an issue with your npm, you should have that http://gomh.se/p/d5166b@raw

**Comment by magne4000** [comment]
Probably a memory or swap issue on your machine

**Comment by disconsented** [comment]
Sounds like I am SOL then

**Comment by magne4000** [comment]
I would tell you to try to make you swap bigger, but if npm fails, i assume that the node process running quassel-webserver will fail too :disappointed:
Node likes to eat your RAM.

**Comment by disconsented** [comment]
Ah well thanks anyway

**Comment by disconsented** [comment]
https://www.digitalocean.com/community/tutorials/how-to-configure-virtual-memory-swap-file-on-a-vps
I forgot that was a thing
