### ISSUE TITLE
Input box slowly recedes off the screen on latest Chrome Beta

### ISSUE THREAD

**Issue by ColtonDRG** [magne4000/quassel-webserver#57]
On the latest Chrome Beta, the input box slowly recedes down off the screen. The longer the selected buffer's loaded backlog, the worse it gets. I am using Chrome version 43.0.2357.65 beta (64-bit). I also have the latest version of quassel-webserver (I performed an update just before taking the following screenshots).

Screenshot from a buffer with a small amount of backlog loaded:
![screenshot-1](https://cloud.githubusercontent.com/assets/5587661/7696644/5adb3b66-fdbc-11e4-969a-eca892afd3b8.png)

Screenshot from a buffer with a lot of backlog loaded:
![screenshot-2](https://cloud.githubusercontent.com/assets/5587661/7696653/66c0e5a2-fdbc-11e4-9492-0295367ee569.png)

I have blurred the message text in these screenshots for obvious reasons. Each screenshot shows the area from a few lines above the input box to the bottom of the window. As you can see, the input box is smaller than usual, but still usable in the first screenshot, but in the second one it is only a couple pixels tall and completely unusable. I tried it with both the default theme, and the solarized dark one. Both have the same result. I have no idea what could be causing this.

**Comment by magne4000** [comment]
I remember somebody had the same issue and fixed this by adding some min-height. So that's what I did there.

**Comment by ColtonDRG** [comment]
Alright. I'll update again now. Thanks!

**Comment by magne4000** [comment]
I forgot to publish the new version of libquassel to npm ... So now you can update (`npm update`) and you should have the fix :)

**Comment by ColtonDRG** [comment]
Ah, I just ran git pull then npm update and it worked fine. Speaking of, my server is running Arch, and I have been thinking of setting up an AUR package to make it easier for others with Arch. Since Ubuntu is using systemd for init now, it would probably be a good idea to include an init script for systemd.

**Comment by magne4000** [comment]
I agree :arrow_right: #58
