### ISSUE TITLE
Can't connect to core

### ISSUE THREAD

**Issue by bauerj** [magne4000/quassel-webserver#59]
When I enter my login credentials and click on 'Connect', nothing happens. No error, no request and sadly not a chat window.

Server console:

    bauerj@bauerj ~www/quassel-webserver (git)-[master] # node app
	GET / 200 820.004 ms - 12419
	GET /stylesheets/bootstrap.min.css 200 603.110 ms - 118036
	GET /stylesheets/fonts.css 200 4.867 ms - 1818
	GET /stylesheets/theme-default.css 200 267.585 ms - 16382
	GET /javascripts/jquery-2.1.3.min.js 200 2.079 ms - 84320
	GET /javascripts/bootstrap-tokenfield.min.js 200 3.389 ms - 17505
	GET /javascripts/angular.min.js 200 467.737 ms - 125499
	GET /javascripts/favico-0.3.6.min.js 200 1.296 ms - 9014
	GET /javascripts/ngSocket.js 200 1.521 ms - 2757
	GET /javascripts/events.js 200 1.186 ms - 7858
	GET /javascripts/angular-sanitize.js 200 2.055 ms - 24730
	GET /javascripts/angular-dnd.min.js 200 1.423 ms - 2786
	GET /javascripts/angular-notify.min.js 200 1.200 ms - 2820
	GET /javascripts/libquassel.js 200 4.977 ms - 63239
	GET /javascripts/json-patch.js 200 1.775 ms - 14272
	GET /javascripts/angular-init.js 200 1.631 ms - 5744
	GET /javascripts/angular-directive.js 200 18.501 ms - 13183
	GET /javascripts/angular-filter.js 200 2.088 ms - 10059
	GET /javascripts/angular-controller.js 200 2.938 ms - 25841
	GET /javascripts/ui-bootstrap-tpls-0.12.0.min.js 200 2.420 ms - 65175
	GET /fonts/glyphicons-halflings-regular.woff2 200 2.023 ms - 18028
	GET /stylesheets/fonts/Roboto-Light-webfont.woff 200 207.766 ms - 105544
	GET /stylesheets/fonts/Roboto-Regular-webfont.woff 200 258.341 ms - 105700
	GET /stylesheets/fonts/DroidSansMono-webfont.woff 200 1.752 ms - 11744
	GET /images/hide-pane-left.png 200 0.899 ms - 271
	GET /stylesheets/fonts/RobotoCondensed-Regular-webfont.woff 200 244.410 ms - 109020
	GET /images/hide-pane-right.png 200 7.524 ms - 262
	GET /images/quassel-logo.png 200 2.071 ms - 511
	GET /stylesheets/bootstrap.min.css 304 3.957 ms - -
	GET /stylesheets/fonts.css 304 1.248 ms - -
	GET /stylesheets/theme-default.css 304 2.657 ms - -
	GET /javascripts/angular-dnd.min.js.map 404 84.233 ms - 1479

Browser console:

    AngularJS loaded
    CONNECTED

Version: 	

    bauerj@bauerj ~www/quassel-webserver (git)-[master] # git log  -n 1
	commit 10075052a816822c4e703dbbe548e731ea53d8fa
	Author: Jol Charles <joel.charles91@gmail.com>
	Date:   Tue May 19 09:08:13 2015 +0200

	    Fixes input box changing height. Fixes #57

Browser: Google Chrome version 42.0.2311.152 m

**Comment by willrea** [comment]
What version of node.js are you using? 
I had an old version and it did this same thing. Updating to a current release fixed it.

**Comment by bauerj** [comment]
bauerj@bauerj ~www/quassel-webserver (git)-[master] # node --version
    v0.12.4

If I'm not mistaken, that should be the latest version.

**Comment by magne4000** [comment]
As @willrea stated, it's usually due to the node version being too old.
Is this a fresh install ? If not, make sure to delete `node_modules` directory and re-run `npm install` with the right version of NodeJS.
Otherwise, try to launch the application like that:

    DEBUG=quassel-webserver,libquassel:*,qtdatastream:* node app

and capture the output to paste it here, perhaps it'll give me a clue on where it stops working.

**Comment by bauerj** [comment]
> Is this a fresh install?

It is. I removed the folder anyway and reinstalled but that doesn't seem to fix the issue.

	bauerj@bauerj ~www/quassel-webserver (git)-[master] # DEBUG=quassel-webserver,libquassel:*,qtdatastream:* node app
	  quassel-webserver Express server listening on port 64443 +0ms
	GET / 200 1110.676 ms - 12419
	GET /stylesheets/bootstrap.min.css 200 371.194 ms - 118036
	GET /stylesheets/fonts.css 200 6.533 ms - 1818
	GET /stylesheets/theme-default.css 200 436.987 ms - 16382
	GET /javascripts/jquery-2.1.3.min.js 200 430.346 ms - 84320
	GET /javascripts/ui-bootstrap-tpls-0.12.0.min.js 200 125.072 ms - 65175
	GET /javascripts/angular.min.js 200 244.426 ms - 125499
	GET /javascripts/bootstrap-tokenfield.min.js 200 25.337 ms - 17505
	GET /javascripts/favico-0.3.6.min.js 200 1.528 ms - 9014
	GET /javascripts/ngSocket.js 200 1.777 ms - 2757
	GET /javascripts/events.js 200 2.885 ms - 7858
	GET /javascripts/angular-sanitize.js 200 29.556 ms - 24730
	GET /javascripts/angular-dnd.min.js 200 10.170 ms - 2786
	GET /javascripts/angular-notify.min.js 200 1.825 ms - 2820
	GET /javascripts/libquassel.js 200 5.465 ms - 63239
	GET /javascripts/json-patch.js 200 1.757 ms - 14272
	GET /javascripts/angular-directive.js 200 3.972 ms - 13183
	GET /javascripts/angular-init.js 200 16.030 ms - 5744
	GET /javascripts/angular-filter.js 200 20.987 ms - 10059
	GET /javascripts/angular-controller.js 200 20.667 ms - 25841
	GET /fonts/glyphicons-halflings-regular.woff2 200 5.346 ms - 18028
	GET /stylesheets/fonts/DroidSansMono-webfont.woff 200 2.054 ms - 11744
	GET /stylesheets/fonts/Roboto-Light-webfont.woff 200 249.684 ms - 105544
	GET /images/hide-pane-left.png 200 1.732 ms - 271
	GET /stylesheets/fonts/Roboto-Regular-webfont.woff 200 288.313 ms - 105700
	GET /images/hide-pane-right.png 200 4.307 ms - 262
	GET /stylesheets/fonts/RobotoCondensed-Regular-webfont.woff 200 211.392 ms - 109020
	GET /images/quassel-logo.png 200 8.081 ms - 511
	GET /stylesheets/theme-darksolarized.css 200 195.096 ms - 17943
	GET /stylesheets/bootstrap.min.css 304 4.383 ms - -
	GET /stylesheets/fonts.css 304 1.377 ms - -
	GET /stylesheets/theme-darksolarized.css 304 2.410 ms - -
	GET /javascripts/angular-dnd.min.js.map 404 95.897 ms - 1479


Doesn't look like that's something helpful. :pensive:

**Comment by bauerj** [comment]
quassel/core.log:

    2015-05-24 23:56:57 Info: Client connected from ::FFFF:D472:3007%0
    2015-05-24 23:56:57 Warning: Peer tried to send package larger than max package size!
    2015-05-24 23:56:57 Warning: Disconnecting ::FFFF:D472:3007%0
    2015-05-24 23:56:57 Info: Non-authed client disconnected. ::FFFF:D472:3007%0

**Comment by magne4000** [comment]
yup, that's what I was thinking of, your core is too old, you need at least 0.9.x, doesn't know the exact minimum version though, sorry :confused:

**Comment by bauerj** [comment]
Okay, that's no problem for me.

Maybe you should state that in the README or better yet show an error message if that's possible.

**Comment by magne4000** [comment]
Refer to #60

**Comment by JoBilert** [comment]
Hey, sorry for reopening that thread.

But I work with a dockerized version of quassel-core (v0.14.0) and quassel-web and get the message ` Disconnecting: "Peer tried to send package larger than max package size!"` on my core.That is when I set the URL of my quassel-core in the quassel-web config.

When I set the IP of the quassel-core as target, I can reach it under the local-IP but when I try thew URL of my qussel web I get
`Error: No status code was provided even though one was expected.` in the Browser and `Socket error 13: Error during SSL handshake: error:0A000076:SSL routines::no suitable signature algorithm` in the quassel-core log

It may have something to do with the containers being behind NGINX Proxy Manager, but I am not sure.

Can anybody help?

**Comment by mtrolley** [comment]
@JoBilert - I have the same problem as you: https://discourse.linuxserver.io/t/quassel-web-cant-connect-to-quassel-core-ssl-error/7857

I'm starting with LSIO to see if anyone there can help, otherwise I think a new issue should be opened here. I doubt you'll get any help on this issue since it's 8 years old.
