### ISSUE TITLE
Add an option to show full hostmasks on part/quit/joins etc

### ISSUE THREAD

**Issue by karan42** [magne4000/quassel-webserver#65]
If there's an option or a way to show this, it would be great for big screens, where screen real estate isn't a big enough of a deal.

**Comment by magne4000** [comment]
I was thinking, perhaps I could add a tooltip on nicks to display detailed info, like full hostmask

**Comment by karan42** [comment]
A tooltip would be nice in the nicklist, like "quasselclient" does it, i use the hostmask on quit/joins a lot too (btw i can't code, and just submit issues, i hope that's ok, not trying to create problems here)

**Comment by magne4000** [comment]
It should be easy to add this parameter in the browser (and also the tooltip on the nicklist, that I should have already done but forgot ...)
I'll add a checkbox "Display full hostmask on join/part/quit"

**Comment by karan42** [comment]
You're the man, I mean dev xD

**Comment by magne4000** [comment]
Fixed by 2703b50
