### ISSUE TITLE
Tab completion works for nicks that have left too.

### ISSUE THREAD

**Issue by karan42** [magne4000/quassel-webserver#66]
Tab completion should fail for nicks that have left the channel. Instead if a nick has quit you can still tab complete their name.

**Comment by Zren** [comment]
Easy enough to do.

Just add `if (!scope.buffer.nickUserMap[nick]) continue` round [here](https://github.com/magne4000/quassel-webserver/blob/master/public/javascripts/angular-directive.js#L174).
