### ISSUE TITLE
Redirect HTTP requests to HTTPS on the SSL/TLS server

### ISSUE THREAD

**Issue by kalaksi** [magne4000/quassel-webserver#69]
I noticed that if I use SSL/TLS on the server but don't type the "https" on the URL, I receive an empty response. This happened to me when I first tried to use quassel-webserver and I initially thought there was a problem with the server. The request didn't generate any output to logs either so it wasn't obvious what was wrong, but after a while I realised that the protocol should be HTTPS. 

This might be an actual problem for non-technical users.
Would be better if the server redirected the client to use HTTPS instead.

**Comment by magne4000** [comment]
Will see if this is doable like here http://www.tonyerwin.com/2014/09/redirecting-http-to-https-with-nodejs.html

**Comment by magne4000** [comment]
You can fix this by issuing `npm install`, it will install `httpolyglot` and add support for the redirection
