### ISSUE TITLE
Server "Killed" after sending some backlog

### ISSUE THREAD

**Issue by disconsented** [magne4000/quassel-webserver#70]
https://gist.github.com/disconsented/1c6dd8696ad3804c33b0#file-gistfile1-txt-L95
Should have all the information needed, any ideas on how to resolve this?

**Comment by magne4000** [comment]
I think that your problem is that you does not have enough memory to run it. See [#56](https://github.com/magne4000/quassel-webserver/issues/56#issuecomment-103401704)

**Comment by disconsented** [comment]
Are you sure about that? I enabled swap with 2GB so unless it uses more than that it should be fine

**Comment by magne4000** [comment]
I don't know how nodejs actually uses swap, but if the process was killed without reason it's generally because of lack of RAM (or perhaps disk space).

**Comment by disconsented** [comment]
As far as I am aware swap is intended to act as RAM once you run out of RAM by utilizing disk space and this is all handled by the OS. Regardless you're right just had a look in the syslog and it was being killed due to running out of memory

**Comment by magne4000** [comment]
Just to let you know, the last version is way more memory efficient (server side), you probably can try to update.

**Comment by disconsented** [comment]
Runs great, thanks for that!
