### ISSUE TITLE
High important activity (like talk) should have more priority over lower

### ISSUE THREAD

**Issue by Civil** [magne4000/quassel-webserver#72]
Currently, sometimes, channels that have messages are color in lower priority activity color (white for dark scheme), but in fact they should be blue (higher priority activity events happened).

**Comment by Civil** [comment]
Also it'll be nice to setup this colors, because I'd prefer to make "low priority activities" light-gray.

**Comment by magne4000** [comment]
I need to rework the channel color highlighting, it's way to complicated :neutral_face:.
Also, changing the colors from the browser is something I wanted to add, but it requires huge modification, so this will not be done any time soon.
So the simple way is to create another theme. To do this, copy the `.less` file of the theme you use and make modification in this new file, then choose this new theme in your browser.

**Comment by Civil** [comment]
Ok, thanks! I'll do that for now.

P.S. Also great project, btw. I'm currently using it almost everyday.

**Comment by magne4000** [comment]
If you already have created a custom theme, you'll need to change some vars:
 * `@highlight-1-color` to `@highlight-medium-color`
 * `@highlight-2-color` to `@highlight-high-color`
 * `@highlight-3-color` to `@highlight-low-color`
