### ISSUE TITLE
Auto-scroll doesn't work

### ISSUE THREAD

**Issue by Gnarfoz** [magne4000/quassel-webserver#75]
In the current version (4b2295707cc6c54a2534dbe7d599d533faf0bcb8) I keep having to scroll channels down manually, auto-scroll doesn't do its thing.

The problem appears to be limited (or mostly occur) for channels I'm currently looking at.
If it's a different buffer that I switch to, it seems to scroll to the right place.

**Comment by magne4000** [comment]
Which browser are you using ? On which OS ?

**Comment by Gnarfoz** [comment]
I'm sorry, I knew I should have included more details. :innocent: 

Chrome Version 46.0.2490.22 beta-m (64-bit)
On Windows 7.

**Comment by Gnarfoz** [comment]
Seems to have worked so far, thanks! :+1:
