### ISSUE TITLE
Not working through an Apache reverse proxy

### ISSUE THREAD

**Issue by ColtonDRG** [magne4000/quassel-webserver#76]
When I click connect through an Apache reverse proxy it does nothing. It works if I connect directly to the quassel-webserver. It also used to work before I updated it. Any idea what's going on?

**Comment by ColtonDRG** [comment]
This might be useful. When I click the connect button in the interface I get this error in Chrome's console
POST https://ts.drg.li/api/vm/net/connect 404 (Not Found)

**Comment by TheDoctorsLife** [comment]
hmm, I also get issues, although they are different between chromium and Firefox, the errors don't show when I connect directly. (Using nginx reverse proxy)

Firefox: 
![firefox](http://i.imgur.com/N4j5tA9.png)

Chrome:
![Chrome](http://i.imgur.com/vcFhKlC.png)

Hope this helps...

**Comment by ColtonDRG** [comment]
Hm. That's odd because I didn't get any of those errors, only the POST error.
I also got similar errors in both browsers.
![snapshot31](https://cloud.githubusercontent.com/assets/5587661/9977311/3bb9df12-5ebf-11e5-87c4-84e73421c08e.png)
![snapshot32](https://cloud.githubusercontent.com/assets/5587661/9977312/3bc056da-5ebf-11e5-944d-10cb920ef66c.png)

**Comment by TheDoctorsLife** [comment]
Hmm, I'll have to see why I am getting those 503 errors, I'll post a console logs once my system finishes booting

**Comment by magne4000** [comment]
The only error it fixes is the 404 error for `/api/vm/net`.
Other errors probably come from misconfigured reverse proxy.

**Comment by ColtonDRG** [comment]
Hm... It still doesn't work for me. I am getting a different error this time.
![snapshot41](https://cloud.githubusercontent.com/assets/5587661/10011057/13fcd584-60b2-11e5-9de4-55ae8e2156c4.png)
![snapshot42](https://cloud.githubusercontent.com/assets/5587661/10011058/140c0b44-60b2-11e5-90a3-dd356df36585.png)

**Comment by magne4000** [comment]
Same as #78

**Comment by ColtonDRG** [comment]
Cool. Thanks.

**Comment by magne4000** [comment]
@ColtonDRG Do you have the error if you try to connect directly to quassel-webserver and not through the reverse proxy ?

**Comment by ColtonDRG** [comment]
Nope. I noticed from the other issue that it has something to do with the config. The information posted on the README is for nginx though, and I'm using Apache.

**Comment by magne4000** [comment]
I do not have Apache installed anymore, so I can test anything. But I know that you need at least apache 2.4 and some specific configuration for Websockets support.

**Comment by magne4000** [comment]
If you succeed to have a working configuration, could you paste it somewhere, so I can put it in the README ?

**Comment by ColtonDRG** [comment]
Well, I am on Arch stable repos, so I highly doubt I'm out of date in that department. I'll google for that websockets configuration. If I find a solution I'll definitely post it here and you're free to post it in the README.
