### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by HeisSpiter** [magne4000/quassel-webserver#77]
Dear all,

Due to commit 656c1825db4435441c8a0b976812c924ac854804, which makes use of git+ssh to checkout code, it is not possible any longer to resolve the dependency for non developers of the project, the SSH checkout being disabled on GitHub for non committers.
(Cloning issues a permission denied over SSH).

Cheers,

**Comment by Civil** [comment]
```
diff --git a/package.json b/package.json
index 4ec150a..0a27fa3 100644
--- a/package.json
+++ b/package.json
@@ -41,7 +41,7 @@
     "less-middleware": "~2.0.1",
     "libquassel": "*",
     "morgan": "~1.5.1",
-    "net-browserify": "git@github.com:magne4000/net-browserify.git",
+    "net-browserify": "git://github.com/magne4000/net-browserify",
     "nomnom": "~1.8.1",
     "serve-favicon": "~2.2.0"
   },
```

**Comment by HeisSpiter** [comment]
@Civil, you proposal fixes the issue.

**Comment by Civil** [comment]
Sorry I don't have any opportunity to make a PR request with it.

**Comment by magne4000** [comment]
I'll change the syntax
