### ISSUE TITLE
Current git can't connect to quasselcore

### ISSUE THREAD

**Issue by Civil** [magne4000/quassel-webserver#78]
Hi!

When I'm trying to use current git master I'm getting following error (domain changed to example.com, just in case):
```
AngularJS loaded angular-init.js:198:5
Connecting to quasselcore angular-controller.js:517:9
Firefox can't establish a connection to the server at wss://example.com/p/socket?token=76aaf5c3a988e284a9d737bf629a64eb56b0203a121334dd6044f19130e130cc. libquassel.js:18641:0
TCP error error { target: WebSocket, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1442845208757690, originalTarget: WebSocket, explicitOriginalTarget: WebSocket, NONE: 0, CAPTURING_PHASE: 1 } libquassel.js:18664:3
```

**Comment by magne4000** [comment]
Do you have any error in your core logs ?

**Comment by Civil** [comment]
Nope, it's 404 from quasselweb. In it's log I see this:
```
Connected to ::1:4242 (33cb697ddc7e63f4d5cc244a645c87a87e1074d71f76d2034142e24923c6f834)
GET /p/socket?token=33cb697ddc7e63f4d5cc244a645c87a87e1074d71f76d2034142e24923c6f834 404 41.502 ms - 1467
```

and actually error is - 404 from quasselweb.

**Comment by Civil** [comment]
In quasselcore I see only this:
```
2015-09-21 11:09:11 Info: Client connected from ::1%0
2015-09-21 11:09:15 Warning: "Socket error 1: The remote host closed the connection"
2015-09-21 11:09:15 Info: Non-authed client disconnected: ::1%0
```

Also it doesn't matter "unsecure" set to "true" or "false" for quasselweb.

**Comment by magne4000** [comment]
Did you change "prefixpath" in settings file ?

**Comment by Civil** [comment]
Nope, it's empty as it was before.

**Comment by magne4000** [comment]
Also, try running `npm update` once again. If it does not work, try removing `node_modules` folder and resintall all modules with `npm install`. I suspect that the version of libquassel is not the good one.

**Comment by Civil** [comment]
Nothing changed.

**Comment by magne4000** [comment]
Can you paste in some pastebin the content of `node_modules/net-browserify/api.js` ?

**Comment by Civil** [comment]
http://paste.ubuntu.com/12514806/

p.s. I've tried running it on nodejs 0.12.7 and on latest nodejs 4.1.0.

**Comment by magne4000** [comment]
@Civil are you using a reverse proxy ?

**Comment by Civil** [comment]
Yeah, indeed. If I connect directly it works. Though the thing is that it's worked before. Ok, I'll have a look what's wrong in my nginx's config.

**Comment by magne4000** [comment]
I'll paste my nginx config in the README

**Comment by Civil** [comment]
yeah. It was
```
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
```
missing. Worked before, though.
