### ISSUE TITLE
404 on POST /api/vm/net/connect

### ISSUE THREAD

**Issue by infecticide** [magne4000/quassel-webserver#79]
Getting this message in the console output after entering credentials and pressing connect:

root@infecticide:/var/lib/quassel/quassel-webserver# node app.js -m http -p 64443 &
[1] 30699
root@infecticide:/var/lib/quassel/quassel-webserver# GET / 200 585.390 ms - 13052
GET /stylesheets/fonts.css 200 4.293 ms - 1818
GET /stylesheets/bootstrap.min.css 200 21.197 ms - 118036
GET /javascripts/favico-0.3.6.min.js 200 21.898 ms - 9014
GET /javascripts/bootstrap-tokenfield.min.js 200 24.352 ms - 17505
GET /javascripts/jquery-2.1.3.min.js 200 24.698 ms - 84320
GET /javascripts/ui-bootstrap-tpls-0.12.0.min.js 200 24.498 ms - 65175
GET /javascripts/angular.min.js 200 74.037 ms - 145318
GET /javascripts/ngSocket.js 200 2.944 ms - 4918
GET /javascripts/angular-dnd.min.js 200 2.577 ms - 2786
GET /javascripts/angular-notify.min.js 200 2.426 ms - 2820
GET /javascripts/angular-sanitize.js 200 7.530 ms - 24922
GET /javascripts/angular-init.js 200 3.540 ms - 5316
GET /javascripts/angular-filter.js 200 3.169 ms - 7663
GET /javascripts/angular-directive.js 200 3.848 ms - 17494
GET /javascripts/angular-controller.js 200 3.585 ms - 24683
GET /stylesheets/theme-default.css 200 186.225 ms - 16855
GET /javascripts/libquassel.js 200 49.122 ms - 903834
GET /images/quassel-logo.png 200 6.992 ms - 511
GET /fonts/glyphicons-halflings-regular.woff2 200 6.584 ms - 18028
GET /stylesheets/fonts/Roboto-Light-webfont.woff 200 10.902 ms - 105544
GET /stylesheets/fonts/Roboto-Regular-webfont.woff 200 9.750 ms - 105700
POST /api/vm/net/connect 404 47.243 ms - 1547

The webpage does not display any errors, no acknowledgement of an issue, it doesn't do anything.

**Comment by magne4000** [comment]
Your dependencies are not up to date. Do a `npm update`. If this doesn't work, remove `node_modules` folder and reinstall dependencies with `npm install`

**Comment by magne4000** [comment]
Fixed by https://github.com/magne4000/node-libquassel/commit/7afbc90f963f6d7de0cea3f7021fd6f762672f04

**Comment by edrex** [comment]
Hmm I'm seeing the same symptom on the latest HEAD
