### ISSUE TITLE
Messages are being sent multiple times

### ISSUE THREAD

**Issue by Gnarfoz** [magne4000/quassel-webserver#8]
I'm not sure what's causing it, but sometimes, messages are being sent multiple times.

![image](https://cloud.githubusercontent.com/assets/65654/4589861/61c08b0e-5059-11e4-911e-14c7bc8699dc.png)

It happens with a short but noticeable delay.
I've had this happen once before, it was 2 extra messages per message that time, not 1.

![image](https://cloud.githubusercontent.com/assets/65654/4589854/4923a96e-5059-11e4-82b3-5e6f553a3766.png)

(It's not a display issue, I've confirmed that it's actually sending the message multiple times.)

**Comment by magne4000** [comment]
Reopening issue, this happens sometimes on double submit of the login form
