### ISSUE TITLE
Can't collapse the last network in the list

### ISSUE THREAD

**Issue by ashfire908** [magne4000/quassel-webserver#82]
All other networks collapse and expand properly, but when I do it for the last network, the icon changes but it doesn't actually collapse.

Tested with Chrome 45.0.2454.101 and Firefox 41.0 on Arch Linux (latest). Running latest master for the app on nodejs 4.1.1.

**Comment by lub** [comment]
I can't confirm this. node v4.1.2 here. Maybe already fixed?

Clients:
firefox 41.0.1 on windows
internet explorer 11.0.21 on windows

**Comment by ashfire908** [comment]
Well, it still doesn't work for me. Node 4.1.2 w/ Chrome 45.0.2454.101, current master.

**Comment by magne4000** [comment]
Do you still have this issue with latest chrome/chromium ?
