### ISSUE TITLE
User list it not updated after user joined

### ISSUE THREAD

**Issue by Civil** [magne4000/quassel-webserver#84]
Sometimes (quite rare) userlist is not being updated after user joins the channel and I can't use autocompletion, etc. Also user still marked as "offline" in chat list. Reconnecting to quassel-core helps.

**Comment by magne4000** [comment]
I'm totally unable to reproduce this. You don't have some more information on this ?

**Comment by Civil** [comment]
Well, it happens not every time. No erros in the console, though.

My use case is to open quasselweb when I'm at work. There I'm connected to multiple networks (freenode and few others) and sometimes, when Quasselweb runs for quite some time (hours) when user joins a room he's not added to the list of users until I refresh the page and reconnect to quasselcore.

I don't know if there any way to debug this thing more. If you have some info on debugging issue I can try to do that when it'll happen next time.

**Comment by magne4000** [comment]
You can `npm update`, launch the webapp and in the browser javascript console write:
```javascript
window.myDebug = require("debug");
myDebug.enable("*")
```
Restart the browser page and now you should see many debug information.
In order to disable debugging:
```javascript
window.myDebug = require("debug");
myDebug.disable()
```

**Comment by Civil** [comment]
well, something wrong with that:
```
window.myDebug = require("debug");
myDebug.enable("*")
libquassel.js:1 Uncaught Error: Cannot find module 'debug'(…)
```

**Comment by magne4000** [comment]
`npm update` should solve that I think
