### ISSUE TITLE
Rare bug resulting in empty channel list, etc

### ISSUE THREAD

**Issue by Civil** [magne4000/quassel-webserver#90]
It's very rare (one a week, everyday at least one login). Don't know exact steps to reproduce.
Here are messages from console:
```
AngularJS loaded
angular-controller.js:517 Connecting to quasselcore
angular-controller.js:481 Logged in
libquassel.js:19125 ERROR
libquassel.js:19126 Object
alert: Object
message: "Could not decrypt record or bad MAC."
origin: "client"
send: true
toString: ()
__proto__: Object
libquassel.js:19125 ERROR
libquassel.js:19126 Error: write after end(…)
libquassel.js:19125 ERROR
libquassel.js:19126 Error: write after end(…)
```

**Comment by magne4000** [comment]
Could you enable debug mode like in #86 and paste the result the next time you have this issue ?

**Comment by magne4000** [comment]
Hum sorry, I meant #84

**Comment by Civil** [comment]
NP. I'll try to obtain that, when I saw it next time.

**Comment by Civil** [comment]
```
AngularJS loaded
angular-controller.js:525 Connecting to quasselcore
angular-controller.js:489 Logged in
libquassel.js:19748 ERROR
libquassel.js:19749 Objectalert: Objectmessage: "Could not decrypt record or bad MAC."origin: "client"send: truetoString: ()__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()
libquassel.js:19748 ERROR
libquassel.js:19749 Error: write after end(…)
window.myDebug = require("debug");
myDebug.enable("*")
undefined
libquassel.js:19748 ERROR
libquassel.js:19749 Error: write after end(…)
```

**Comment by Civil** [comment]
Also with latest quasselweb it happens most of the time.

**Comment by magne4000** [comment]
This one will be tough :) it somehow fails to decrypt TLS packets; probably comes from forge library. I don't even know if I will be able to fix it.
The only bypass I see for now would be to set `unsecurecore` to `true`, it would deactivate TLS between browser and core, and so avoid the use of forge library.

**Comment by magne4000** [comment]
I made some changes in libquassel, don't know if it will fix the issue, but it is possible. So I recommend that you do a `npm update`

**Comment by Civil** [comment]
I've updated to latest git, did npm update, but still have this problem. Well, looks like for now I'll stick with unsecurecore.

**Comment by Civil** [comment]
I think it's possible to workaround that bug - in case of connection failure or any other SSL errors - just reconnect. Will be slower, but will work.

**Comment by magne4000** [comment]
Does this still happens to you ?

**Comment by Civil** [comment]
Well, I'm actually almost not using quassel-web anymore - only in environments that allows only 80/443 ports, which is quite rare. So I'm honestly don't know.

**Comment by magne4000** [comment]
I'm closing this (I think can't do anything anyway ...). Feel free to reopen this issue if needed.
