### ISSUE TITLE
Creating new themes

### ISSUE THREAD

**Issue by sdfg2** [magne4000/quassel-webserver#93]
Hello,

I've been editing the darksolarized theme to more fit the theme that I like, but I wonder if you could explain how to make an actual new theme for it?

:-)

**Comment by magne4000** [comment]
You should create a copy of https://github.com/magne4000/quassel-webserver/blob/master/public/stylesheets/theme-darksolarized.less, for example `/public/stylesheets/theme-custom.less`, and just put what you need in it.
All variables defined in this file are used by https://github.com/magne4000/quassel-webserver/blob/master/public/stylesheets/style.less (you can consider it as an abstract class that puts default values that you can override in you custom stylesheet)

**Comment by sdfg2** [comment]
Oh, so the less file is sort of compiled into the css file?  That explains why the css file had such horrendous formatting!  I've been editing the resulting css file for darksolarized.

**Comment by magne4000** [comment]
The less file will be automatically compiled yes :)
