### ISSUE TITLE
Channel activity not shown upon initial connect

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#99]
Regardless of whether or not you've looked at a channel, and whether there is unseen backlog, the channel list doesn't show any channel activity until it receives new activity.

**Comment by Zren** [comment]
I think this is caused by `initialBacklogLimit` equaling 0? Does it work if you set it to a higher value?

**Comment by tecknojock** [comment]
my initial backlog limit is 20:

module.exports = {
    default: {
        host: -----,
        port: 4242,
        initialBacklogLimit: 20,
        backlogLimit: 100
    },
    forcedefault: true,
    prefixpath: '',
    unsecurecore: false,
    theme: 'default'
};

**Comment by magne4000** [comment]
You'll need to `git pull` then `npm update` for this fix
